### ISSUE TITLE
[Enhancement] Add support for Humdifiers

### ISSUE THREAD

**Issue by joaopedros2** [t0bst4r/home-assistant-matter-hub#100]
I'm experiencing an issue where the "humidifier" entities are not functioning as expected.
It appears they are not compatible, where can I check the list of compatible devices?

**Comment by t0bst4r** [comment]
Hi @joaopedros2 ,
what domain are humidifiers using in Home Assistant? Climate? Climates are currently buggy - i am working on it.
In general you can find a list of supported domains in the README of this project.
https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#supported-domains--device-types

**Comment by joaopedros2** [comment]
I don't know if this is what you intend to see.

![Screenshot_2024-11-10-10-27-47-31_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/fc37ef7f-f97c-4b36-bfe2-e50d254b3c48)

![Screenshot_2024-11-10-10-28-10-00_c3a231c25ed346e59462e84656a70e50.jpg](https://github.com/user-attachments/assets/3576824e-ba44-40d8-a451-e76df0262c59)

**Comment by t0bst4r** [comment]
Thank you! I didn't know that humdifiers have their own domain in Home Assistant.
So yes, they are currently now supported. I keep this issue here as a feature request.

**Comment by KipK** [comment]
It's not supported by Matter on current 1.3 specs. new published matter 1.4 neither.

**Comment by KipK** [comment]
The best way for now would be to make a switch entity from it using a template. With just On Off value, and you keep the device settings exposed on Home Assistant.

**Comment by librehat** [comment]
Or this can be modelled as a "fan" that comes with a humidity sensor?
