### ISSUE TITLE
Switch error when using google assistant

### ISSUE THREAD

**Issue by nhok3296** [t0bst4r/home-assistant-matter-hub#112]
When using google voice assistant it turns off all 3 buttons on one switch, but it still turns on correctly

**Comment by t0bst4r** [comment]
Can you share some details? What 3 buttons do you mean? What is happening in detail?

**Comment by nhok3296** [comment]
> Can you share some details? What 3 buttons do you mean? What is happening in detail?

I have a Tuya Zigbee switch, when I call Google Assistant to help me turn off 1 of the 3 buttons on that switch, it will turn off all the remaining buttons.
![Uploading 20241112_094739.jpg…]()

**Comment by t0bst4r** [comment]
The screenshot you attached wasn't finished uploading when you posted your answer. So its missing.

To sum it up:
- you have ONE hardware device (tuya zigbee)
- in Home assistant this device has THREE entities?
- you expose all three entities to matter -> therefore you have THREE devices in google home
- you tell google to turn off one of those devices, but it turns off all three

Do they have the same name?
Does it also happen when calling `switch.turn_on` for ONE of those entities using the HA developer tools?

**Comment by nhok3296** [comment]
> The screenshot you attached wasn't finished uploading when you posted your answer. So its missing.
> 
> To sum it up:
> 
> * you have ONE hardware device (tuya zigbee)
> * in Home assistant this device has THREE entities?
> * you expose all three entities to matter -> therefore you have THREE devices in google home
> * you tell google to turn off one of those devices, but it turns off all three
> 
> Do they have the same name? Does it also happen when calling `switch.turn_on` for ONE of those entities using the HA developer tools?

I gave those 3 entities 3 different names, when turned on nothing happens, only when turned off does it happen. With cloud it's normal

**Comment by nhok3296** [comment]
> Can you please
> 
> 1. upgrade to the latest version
> 2. Set the log level to debug
> 3. Attach a log file which exactly includes the time where this happens

Thank you, everything is fine in version 36

**Comment by nhok3296** [comment]
> Can you please
> 
> 1. upgrade to the latest version
> 2. Set the log level to debug
> 3. Attach a log file which exactly includes the time where this happens

[491eb00d_hamh_2024-11-18T04-20-06.912Z.log](https://github.com/user-attachments/files/17794560/491eb00d_hamh_2024-11-18T04-20-06.912Z.log)
switch.pn1_1 and switch.pn1_2

**Comment by nhok3296** [comment]
> To be honest, i dont know why this happens. Does it still happen with the latest version?
> 
> It looks more like Google Assistant is actually calling all three devices. In the log we can see that it actually received 3 commands from the matter controller (google assistant).
> 
> Do you have any grouping configured? Or name clashes with groups / rooms other devices?
Same configuration but cloud service has no problem

**Comment by t0bst4r** [comment]
Looking at your logs, google home sends the command to all three devices.


**input_boolean.baothuc**

```
[ 2024-11-18T04:19:38.514Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: New exchange channel: udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 protocol: 1 id: 22637 session: secure/55696 peerSessionId: 55696 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
[ 2024-11-18T04:19:38.515Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Message « id: 55696/22637/240313997 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024001024010624020018350118181824ff0b18
[ 2024-11-18T04:19:38.516Z ] [ DEBUG ] [ matter.js / InteractionServer                      ]: Received invoke request from udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 with 1 commands: OnOffPlugInUnit(0x10)/OnOff(0x6)/off(0x0), suppressResponse=false
[ 2024-11-18T04:19:38.518Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke c881aacd8c164103becae58765554733.aggregator.input_boolean_baothuc.onOff.off online#e52e68d@29b89ac6 (no payload)
[ 2024-11-18T04:19:38.519Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68d@29b89ac6 locked c881aacd8c164103becae58765554733.aggregator.input_boolean_baothuc.onOff.state
[ 2024-11-18T04:19:38.520Z ] [ DEBUG ] [ HomeAssistantClient                                ]: Calling action 'homeassistant.turn_off' for target {"entity_id":"input_boolean.baothuc"} with data {}
```

**switch.pn1_2**

```
[ 2024-11-18T04:19:38.522Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: New exchange channel: udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 protocol: 1 id: 22638 session: secure/55696 peerSessionId: 55696 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
[ 2024-11-18T04:19:38.523Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Message « id: 55696/22638/240313998 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024000a24010624020018350118181824ff0b18
[ 2024-11-18T04:19:38.524Z ] [ DEBUG ] [ matter.js / InteractionServer                      ]: Received invoke request from udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 with 1 commands: OnOffPlugInUnit(0xa)/OnOff(0x6)/off(0x0), suppressResponse=false
[ 2024-11-18T04:19:38.525Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke c881aacd8c164103becae58765554733.aggregator.switch_pn1_2.onOff.off online#e52e68e@29b89ac6 (no payload)
[ 2024-11-18T04:19:38.526Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68e@29b89ac6 locked c881aacd8c164103becae58765554733.aggregator.switch_pn1_2.onOff.state
[ 2024-11-18T04:19:38.527Z ] [ DEBUG ] [ HomeAssistantClient                                ]: Calling action 'homeassistant.turn_off' for target {"entity_id":"switch.pn1_2"} with data {}
```

**switch.pn1_1**
```
[ 2024-11-18T04:19:38.529Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: New exchange channel: udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 protocol: 1 id: 22639 session: secure/55696 peerSessionId: 55696 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
[ 2024-11-18T04:19:38.532Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Message « id: 55696/22639/240313999 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024000924010624020018350118181824ff0b18
[ 2024-11-18T04:19:38.533Z ] [ DEBUG ] [ matter.js / InteractionServer                      ]: Received invoke request from udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 with 1 commands: OnOffPlugInUnit(0x9)/OnOff(0x6)/off(0x0), suppressResponse=false
[ 2024-11-18T04:19:38.535Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke c881aacd8c164103becae58765554733.aggregator.switch_pn1_1.onOff.off online#e52e68f@29b89ac6 (no payload)
[ 2024-11-18T04:19:38.536Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68f@29b89ac6 locked c881aacd8c164103becae58765554733.aggregator.switch_pn1_1.onOff.state
[ 2024-11-18T04:19:38.537Z ] [ DEBUG ] [ HomeAssistantClient                                ]: Calling action 'homeassistant.turn_off' for target {"entity_id":"switch.pn1_1"} with data {}
[ 2024-11-18T04:19:38.553Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68d@29b89ac6 committed and unlocked 1 resource
```

In each of those three logs, the first 5 lines indicate that a command from Google Assistant was received.
Can you verify that the IPv6 address `fe80::2f6:20ff:fe88:6be2` is your Google Assistant device?

It is not a problem with the hub, it is a problem with Google Home.
Somehow Google thinks you want to turn off all those devices.

**Comment by nhok3296** [comment]
> Looking at your logs, google home sends the command to all three devices.
> 
> **input_boolean.baothuc**
> 
> ```
> [ 2024-11-18T04:19:38.514Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: New exchange channel: udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 protocol: 1 id: 22637 session: secure/55696 peerSessionId: 55696 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
> [ 2024-11-18T04:19:38.515Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Message « id: 55696/22637/240313997 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024001024010624020018350118181824ff0b18
> [ 2024-11-18T04:19:38.516Z ] [ DEBUG ] [ matter.js / InteractionServer                      ]: Received invoke request from udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 with 1 commands: OnOffPlugInUnit(0x10)/OnOff(0x6)/off(0x0), suppressResponse=false
> [ 2024-11-18T04:19:38.518Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke c881aacd8c164103becae58765554733.aggregator.input_boolean_baothuc.onOff.off online#e52e68d@29b89ac6 (no payload)
> [ 2024-11-18T04:19:38.519Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68d@29b89ac6 locked c881aacd8c164103becae58765554733.aggregator.input_boolean_baothuc.onOff.state
> [ 2024-11-18T04:19:38.520Z ] [ DEBUG ] [ HomeAssistantClient                                ]: Calling action 'homeassistant.turn_off' for target {"entity_id":"input_boolean.baothuc"} with data {}
> ```
> 
> **switch.pn1_2**
> 
> ```
> [ 2024-11-18T04:19:38.522Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: New exchange channel: udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 protocol: 1 id: 22638 session: secure/55696 peerSessionId: 55696 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
> [ 2024-11-18T04:19:38.523Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Message « id: 55696/22638/240313998 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024000a24010624020018350118181824ff0b18
> [ 2024-11-18T04:19:38.524Z ] [ DEBUG ] [ matter.js / InteractionServer                      ]: Received invoke request from udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 with 1 commands: OnOffPlugInUnit(0xa)/OnOff(0x6)/off(0x0), suppressResponse=false
> [ 2024-11-18T04:19:38.525Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke c881aacd8c164103becae58765554733.aggregator.switch_pn1_2.onOff.off online#e52e68e@29b89ac6 (no payload)
> [ 2024-11-18T04:19:38.526Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68e@29b89ac6 locked c881aacd8c164103becae58765554733.aggregator.switch_pn1_2.onOff.state
> [ 2024-11-18T04:19:38.527Z ] [ DEBUG ] [ HomeAssistantClient                                ]: Calling action 'homeassistant.turn_off' for target {"entity_id":"switch.pn1_2"} with data {}
> ```
> 
> **switch.pn1_1**
> 
> ```
> [ 2024-11-18T04:19:38.529Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: New exchange channel: udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 protocol: 1 id: 22639 session: secure/55696 peerSessionId: 55696 active threshold ms: 4000 active interval ms: 300 idle interval ms: 500 maxTransmissions: 5 useMrp: true
> [ 2024-11-18T04:19:38.532Z ] [ DEBUG ] [ matter.js / MessageExchange                        ]: Message « id: 55696/22639/240313999 type: 1/8 acked: undefined reqAck: true duplicate: false payload: 1528002801360215370024000924010624020018350118181824ff0b18
> [ 2024-11-18T04:19:38.533Z ] [ DEBUG ] [ matter.js / InteractionServer                      ]: Received invoke request from udp://fe80::2f6:20ff:fe88:6be2%eno1:5540 on session secure/55696 with 1 commands: OnOffPlugInUnit(0x9)/OnOff(0x6)/off(0x0), suppressResponse=false
> [ 2024-11-18T04:19:38.535Z ] [ INFO  ] [ matter.js / Behavior                               ]: Invoke c881aacd8c164103becae58765554733.aggregator.switch_pn1_1.onOff.off online#e52e68f@29b89ac6 (no payload)
> [ 2024-11-18T04:19:38.536Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68f@29b89ac6 locked c881aacd8c164103becae58765554733.aggregator.switch_pn1_1.onOff.state
> [ 2024-11-18T04:19:38.537Z ] [ DEBUG ] [ HomeAssistantClient                                ]: Calling action 'homeassistant.turn_off' for target {"entity_id":"switch.pn1_1"} with data {}
> [ 2024-11-18T04:19:38.553Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction online#e52e68d@29b89ac6 committed and unlocked 1 resource
> ```
> 
> In each of those three logs, the first 5 lines indicate that a command from Google Assistant was received. Can you verify that the IPv6 address `fe80::2f6:20ff:fe88:6be2` is your Google Assistant device?
> 
> It is not a problem with the hub, it is a problem with Google Home. Somehow Google thinks you want to turn off all those devices.

I'm not sure either, but if you use the cloud, there won't be any problems. I'll wait for the official version and try again later. Thanks. Oh, and if possible, add a room to make it easier to configure.
