### ISSUE TITLE
[Enhancement] configuration of CLI / env arguments per json file

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/home-assistant-matter-hub#115]
### Discussed in https://github.com/t0bst4r/home-assistant-matter-hub/discussions/113

<div type='discussions-op-text'>

<sup>Originally posted by **tam481** November 11, 2024</sup>
Hello
Do you have any plans to support all parameters to be in the json file like Matterbridge?

Parameters such as HAMH_HOME_ASSISTANT_URL etc</div>

**Comment by tam481** [comment]
You are a legend. 

I was thinking perhaps you could have "global" parameters in the external config file. Wouldn't these settings apply to all devices using the hub?

**Comment by t0bst4r** [comment]
Copied from the discussion:
> They are not specific per bridge, so it doesn’t make sense to put it there.
> Anyway I am using yargs to parse cli commands and env variables. I could activate the config property there, which allows having an additional config file for value which are provided as cli or env at the moment.

---

> I was thinking perhaps you could have "global" parameters in the external config file

what external config file do you mean?
The `app.json`? This is intended to be read/written by the app itself. To prevent conflicts, I’d use a different file. You‘ll be able to configure the config file path by yourself, so you could put it in the same location than the storage.

**Comment by t0bst4r** [comment]
Yeah so the config file will look like the parameters you find when running `home-assistant-matter-hub start --help`:

```json
{
  "homeAssistantUrl": "http://192.168.178.23:8123",
  "logLevel": "debug"
}
```

and then you can use either tell the app via cli or via env where to find the config file. 
you can even combine config file, cli param and env. That’s a feature of `yargs` - but I need to activate it first.

**Comment by tam481** [comment]
Any chance you can help me with the token variable to add to the config? Is it "homeAssistantAccessToken": "" ?

I am using the container version and can't run home-assistant-matter-hub start --help

Also, does this version support https yet? If not, I will raise a request :-)

**Comment by t0bst4r** [comment]
> Any chance you can help me with the token variable to add to the config? Is it "homeAssistantAccessToken": "" ?

yes that‘ll probably be correct 


> Also, in terms of the env configuration, does this look correct to you?
> 
> ```
> volumes: 
>   - "$PWD/conf/matterhub:/data:ro"
> environment:
>   HAMH_CONFIG_FILE: /data/config.json
> ```

like that or similar. As I said: it is not yet working, I need to activate (and test) this feature first.
