### ISSUE TITLE
[Enhancement] Use entity_id if friendly name is missing

### ISSUE THREAD

**Issue by backcountrymountains** [t0bst4r/home-assistant-matter-hub#117]
![image](https://github.com/user-attachments/assets/6aa669fe-479c-4bff-b13d-8ec1ff52b7ce)

I have some ```input_boolean``` entities that I didn't name in my yaml config. They entity_id shows up but the lack of a name causes them to all be "Unknown Entity". I Can't tell them apart when I add them to Alexa, because Alexa only shows the name "Unknown Entity" for both devices. Dunno if there's a way to just use the entity_id if there is no HA name. 

Obviously, this is my fault for not giving them a name, but maybe there are other instances where defaulting to Name=Entity_ID when there is no defined HA name would be useful.

BTW, THIS IS AMAZING! Alexa is slow and sometimes flaky pinging commands back and forth between my server and bezos HQ when I ask her to do something, but using this integration/addon seems to really be a huge improvement!

TYSM!

**Comment by t0bst4r** [comment]
You are right, I'll change that! 🙂
