### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by sierralx** [t0bst4r/home-assistant-matter-hub#121]
}
[ 2024-11-12T08:02:14.152Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back initialize<016a6c8567fd4e599aec31a04411a352.aggregator.climate_ecobee_thermostat>#cf due to error: Behaviors have errors
home-assistant-matter-hub start
start the application
Options:
  --help                         Show help                             [boolean]

**Comment by t0bst4r** [comment]
Hi @sierralx 

can you add some more logs?
This is just some fracture of a log 😀
