### ISSUE TITLE
Since alpha.28 google home often cannot control devices and is often offline

### ISSUE THREAD

**Issue by datvista** [t0bst4r/home-assistant-matter-hub#128]
Since alpha.28 google home often cannot control devices and is often offline
![Screenshot_20241113-072437](https://github.com/user-attachments/assets/23727217-b11d-4c7c-bccf-15d4171d0801)

**Comment by datvista** [comment]
[logs-3.txt](https://github.com/user-attachments/files/17724375/logs-3.txt)

**Comment by datvista** [comment]
Use CPU a lot 
[logs-4.txt](https://github.com/user-attachments/files/17724464/logs-4.txt)

**Comment by datvista** [comment]
But why is my google home still relatively stable with alpha 27?

**Comment by Apollon77** [comment]
@t0bst4r What were the changes between 27 and 28?

**Comment by Apollon77** [comment]
Maybe share a comparism log from start on for some minutes with 27 and 28

**Comment by 011V32** [comment]
> What were the changes between 27 and 28?

https://github.com/t0bst4r/home-assistant-matter-hub/compare/v3.0.0-alpha.27...v3.0.0-alpha.28

**Comment by Apollon77** [comment]
Interesting ... none of these changes should be low level enough. So if you now go back to .27 it works? and with .28 not?

**Comment by datvista** [comment]
Thank you , updated alpha.30, pretty ok with me, still testing
