### ISSUE TITLE
Error Starting Integration

### ISSUE THREAD

**Issue by SalvatoreITA** [t0bst4r/home-assistant-matter-hub#130]
Hi thanks for your great work, I integrated my devices on my Google Home assistant, they are seen and detected but as soon as I try to turn on a switch shortly after the integration stops and stops working, I attach log. Thanks

[log.log](https://github.com/user-attachments/files/17737081/log.log)

**Comment by pbn42** [comment]
Hi,

I had the same problem, it seems that it was because i had a climate device (see log)

By removing it from the app.json file, everything works fine !

[491eb00d_hamh_2024-11-13T20-46-55.453Z.log](https://github.com/user-attachments/files/17739084/491eb00d_hamh_2024-11-13T20-46-55.453Z.log)

**Comment by SalvatoreITA** [comment]
Hi thanks for your reply, I just tried with a single wled bulb, as soon as I try to turn it on the bulb lights up but immediately the integration crashes I excluded everything there is only one visible light I attach the new log.

![Schermata del 2024-11-13 22-33-14](https://github.com/user-attachments/assets/dc2ce4a9-ef9e-42b5-85fe-e5c0199bf3af)

[491eb00d_hamh_2024-11-13T21-33-55.742Z.log](https://github.com/user-attachments/files/17739550/491eb00d_hamh_2024-11-13T21-33-55.742Z.log)

**Comment by t0bst4r** [comment]
This should have been fixed with alpha.29 - anyway there is another bug. in alpha.30 i just added debug logs to find more about the new error. This will be tracked in #134
