### ISSUE TITLE
Include/Exclude by entity name

### ISSUE THREAD

**Issue by Milinator** [t0bst4r/home-assistant-matter-hub#131]
Thank you for this great AddOn!

One feature I’m really missing: I'd like the ability to have all devices disabled for Alexa by default, allowing me to selectively enable specific entities or devices. Currently, it seems like I can only expose entire domains (e.g.), which then requires me to manually remove unwanted devices in the Alexa app. Is there any way to make it so that all devices are hidden by default, with an option to enable only chosen entities/devices?

Thank you for considering this feature request, and thanks for your hard work on this project!

**Comment by pbn42** [comment]
> Thank you for this great AddOn!
> 
> One feature I’m really missing: I'd like the ability to have all devices disabled for Alexa by default, allowing me to selectively enable specific entities or devices. Currently, it seems like I can only expose entire domains (e.g.), which then requires me to manually remove unwanted devices in the Alexa app. Is there any way to make it so that all devices are hidden by default, with an option to enable only chosen entities/devices?
> 
> Thank you for considering this feature request, and thanks for your hard work on this project!

You can already do this 👍 
In the example bellow, i only expose two entities :)

`{
  "filter": {
    "include": [
      {
        "type": "pattern",
        "value": "switch.prise_chauffage_sdb_haut"
      },
      {
        "type": "pattern",
        "value": "light.prise_cheminee"
      }
    ],
    "exclude": []
  }
}`

**Comment by Milinator** [comment]
> > Thank you for this great AddOn!
> > 
> > One feature I’m really missing: I'd like the ability to have all devices disabled for Alexa by default, allowing me to selectively enable specific entities or devices. Currently, it seems like I can only expose entire domains (e.g.), which then requires me to manually remove unwanted devices in the Alexa app. Is there any way to make it so that all devices are hidden by default, with an option to enable only chosen entities/devices?
> > 
> > Thank you for considering this feature request, and thanks for your hard work on this project!
> 
> You can already do this 👍 
> In the example bellow, i only expose two entities :)
> 
> `{
>   "filter": {
>     "include": [
>       {
>         "type": "pattern",
>         "value": "switch.prise_chauffage_sdb_haut"
>       },
>       {
>         "type": "pattern",
>         "value": "light.prise_cheminee"
>       }
>     ],
>     "exclude": []
>   }
> }`
> 
> 
> 

Oops, thanks for that! 😅
