### ISSUE TITLE
Version 3.0.0 alpha 29 & 30 crashes on startup

### ISSUE THREAD

**Issue by lone-baggie** [t0bst4r/home-assistant-matter-hub#134]
[logs.txt](https://github.com/user-attachments/files/17748826/logs.txt)
Version 29 will not start see logs.version 28 crashed when starting scripts Have reverted to 26 which works fine and is stable

**Comment by Fooose** [comment]
[logs.txt](https://github.com/user-attachments/files/17749679/logs.txt)

same here!

**Comment by TWIX99b** [comment]
same here

[491eb00d_hamh_2024-11-14T14-47-33.807Z.log](https://github.com/user-attachments/files/17750270/491eb00d_hamh_2024-11-14T14-47-33.807Z.log)

**Comment by KipK** [comment]
still crashing with alpha 30, same log as above with HS

**Comment by t0bst4r** [comment]
Thank you! That debug log was helpful!
The problem is that "hs_color" attribute is null when the light is turned off.
I need to fill in the correct "off" value.

Can you try turning that light on and then start the addon?

**Comment by t0bst4r** [comment]
Just released alpha.31.
Can you please give it another try?

**Comment by Milinator** [comment]
The new version works :)
Do you still want logs?

**Comment by t0bst4r** [comment]
If it's working and there's no error, i dont need it.
If you have any errors in the logs, i'd love to see them.
