### ISSUE TITLE
adding to different matter hubs

### ISSUE THREAD

**Issue by tobiimschrank** [t0bst4r/home-assistant-matter-hub#15]
Maybe I got the idea of matter wrong or I am making a mistake here.
I have installed the new version via docker and it works fine after I had some problems especially when adding lights without colors (already found these here).

Now I've added my hub to google home, which didn't work via the QR code, but this might be just my problem, because the QR code worked in smartthings. After that I can easily control the device. Works really well.

Now I also wanted to add the hub to SmartThings, as I thought this is something I can do with matter. But the QR Code now has an overlay and says "Commissioned".
Is this a problem with google home or do I have to create a hub each time I want to add it to something else even if I want to use the same configuration?

**Comment by t0bst4r** [comment]
yeah unfortunately you cannot use the QR code twice. that why i added an overlay. but you can use the first connected controller to share the matter hub with another controller.

e.g. with alexa you can open the alexa app and go to the hub device. there you can share the app with e.g. apple home (somewhere deep in the settings of the alexa app).

I'll still need to create the FAQs / how-tos.

**Comment by tobiimschrank** [comment]
This is what I am doing right now and it works like a charm (As long as I don't add a device that creates an error :D)
