### ISSUE TITLE
[Enhancement] Bridge configuration via config json file

### ISSUE THREAD

**Issue by tam481** [t0bst4r/home-assistant-matter-hub#162]
Please allow the bridge config to be created in a json file that can be modified via the UI if possible.

**Comment by t0bst4r** [comment]
I will probably not implement it like this.
But if that's REALLY necessary for you, you can have a look at the app-config file (`/data/app.json` in docker).
If it is missing you need to create one bridge first.

You CAN manipulate this file by hand if you like, but it is not recommended.
The structure will also probably be changed in the future - but the app will update the file structure in that case.
