### ISSUE TITLE
Bug with Window Covers in Matter/SmartThings/Google Home Integration

### ISSUE THREAD

**Issue by Biohospitalix** [t0bst4r/home-assistant-matter-hub#164]
Here is how you can explain your issue on GitHub in English:

I have an issue with my window covers. These covers do not support percentage-based positioning; they only have commands for "up," "down," and "stop." To manage their state, I added a sensor that indicates whether they are open or closed.

I created a YAML configuration for these covers using the cover component with the generic platform.

On Homebridge and Home Assistant, everything works fine.

On Matter, SmartThings, or Google Home, the integration does not work properly.

However, when I use Google Home via the cloud, it works as expected.

It seems like the problem is specifically related to how the configuration or functionality is handled in Matter/SmartThings/Google Home locally.

volet_louis:
      friendly_name: "Volet Louis 2"
      position_template: "{{ (states('binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_25') == 'off')|int * 100 }}"
      open_cover:
        service: cover.open_cover
        data:
          entity_id: cover.volet_louis
      close_cover:
        service: cover.close_cover
        data:
          entity_id: cover.volet_louis
      stop_cover:
        service: cover.stop_cover
        data:
          entity_id: cover.volet_louis

**Comment by t0bst4r** [comment]
Can you describe what exactly is not working?
Can you share the attributes (Home Assistant -> dev tools -> state -> search for the entity) of the generic cover) ?
Are there any error logs in the addon?

**Comment by Biohospitalix** [comment]
![image](https://github.com/user-attachments/assets/698052ad-71c7-4422-8633-fc6eaeb0c875)

Nothing works. In smartthings I have 3 buttons, open, close and stop and one position from 0 to 100%
Position is made by a sensor. When reach it's close.

`    volet_bureau:
      friendly_name: "Volet Bureau 2"
      unique_id: VWoQmdAes2Y8wZ0fsM13
      position_template: "{{ (states('binary_sensor.lumi_lumi_sensor_magnet_aq2_opening_21') == 'off')|int * 100 }}"
      open_cover:
        service: cover.open_cover
        data:
          entity_id: cover.volet_bureau
      close_cover:
        service: cover.close_cover
        data:
          entity_id: cover.volet_bureau
      stop_cover:
        service: cover.stop_cover
        data:
          entity_id: cover.volet_bureau`

**Comment by KipK** [comment]
You don't need to fake the position attribute with a template on HA. Just keeping the open/closed state is sufficient.

"supported_feature" will be 3 then.

Because if you add position, then HA will add the set position command too.

**Comment by t0bst4r** [comment]
> Nothing works.

- Do you see the cover in the matter web ui?
- If yes, do you **see** the cover in google home after pairing?
- If yes, what buttons do you see? What happens when you press them?
 
 Please answer **all** of the above questions, and attach the addon logs and your bridge configuration from within the matter web ui.

**Comment by Biohospitalix** [comment]
> You don't need to fake the position attribute with a template on HA. Just keeping the open/closed state is sufficient.
> 
> "supported_feature" will be 3 then.
> 
> Because if you add position, then HA will add the set position command too.

Yes but without a template i can't keep position when using cover trigger.

**Comment by Biohospitalix** [comment]
> > Nothing works.
> 
> * Do you see the cover in the matter web ui?
> * If yes, do you **see** the cover in google home after pairing?
> * If yes, what buttons do you see? What happens when you press them?
> 
> Please answer **all** of the above questions, and attach the addon logs and your bridge configuration from within the matter web ui.

> * Do you see the cover in the matter web ui?
Yes
![image](https://github.com/user-attachments/assets/f23a4ade-eaaa-4de1-9d9d-5e882b67db28)

Yes
All button are grey. I can't interact with them. When using google home cloud integration it's ok

**Comment by MitoKafander** [comment]
Smart blinds for me now show up only as UP and DOWN. In earlier versions I could set them at a specific height just like in home assistant. 
I could even use google assistant to specify the exact number between 0 and 100 to state how much I wanted the blinds to be open. 
Now there are just two options - fully open or fully closed. 
Previously was better I think.

**Comment by digiolin** [comment]
@t0bst4r maybe we need to consider the value of supported features. In my case in the state if the cover in HA it shows:

`supported_features: 11`

from [here](https://github.com/home-assistant/core/blob/1635074aae275b9fb3377e4ffadfd674db3311b5/homeassistant/components/cover/__init__.py#L129)

```
    OPEN = 1
    CLOSE = 2
    SET_POSITION = 4
    STOP = 8
    OPEN_TILT = 16
    CLOSE_TILT = 32
    STOP_TILT = 64
    SET_TILT_POSITION = 128
```

so mine is 11 in binary is 1011

Then:

| Constant            | Decimal Value | Binary Representation |
|---------------------|---------------|-----------------------|
| OPEN                | 1             | 0000 0001             |
| CLOSE               | 2             | 0000 0010             |
| SET_POSITION        | 4             | 0000 0100             |
| STOP                | 8             | 0000 1000             |
| OPEN_TILT           | 16            | 0001 0000             |
| CLOSE_TILT          | 32            | 0010 0000             |
| STOP_TILT           | 64            | 0100 0000             |
| SET_TILT_POSITION   | 128           | 1000 0000             |

My covers have OPEN, CLOSE and STOP, but not sure why it shows me just the percentage thing...

**Comment by t0bst4r** [comment]
@Biohospitalix 
> Yes All button are grey. I can't interact with them. When using google home cloud integration it's ok

Can you please verify if IPv6 is enabled in your local network?
Are your running HAOS with the addon, or do you run the docker image?

---

@digiolin 
> Smart blinds for me now show up only as UP and DOWN. In earlier versions I could set them at a specific height just like in home assistant.

This is a different issue (#144), but it should be fixed with the latest version.

**Comment by Biohospitalix** [comment]
Yes I use IPv6 and Matterhub as an add-on.
This works in the Samsung app by doing this:
I indicate 0 or 100% closure and I start the predefined position (0 or 100) . This does not work by shutter when indicating open or close.
![Screenshot_20241201_131638_SmartThings](https://github.com/user-attachments/assets/4ee543a0-4e67-45d8-a330-aaeed8d779fb)
![Screenshot_20241201_131625_SmartThings](https://github.com/user-attachments/assets/4b734039-f2cf-4e54-a6c3-c07d811f135f)
