### ISSUE TITLE
"climate" control

### ISSUE THREAD

**Issue by bamirb** [t0bst4r/home-assistant-matter-hub#166]
I have two AC units.
One that appears in HomeAssistant as "climate.ac1" is a MQTT entry which is identified by the bridge and is controllable
The second appears in HomeAssistant as "climate.ac2" is connected via RS485 (modbus integration) but is not discovered by the bridge.

Can something be done to make "ac2" discovered and controlled?

**Comment by t0bst4r** [comment]
It is hard to find out, but it seems that devices which do net get a "unique_id" from their integration are not exposed in the entity_registry - this is where i get the list of all entities from.

You can check if that's the case by opening the entity's details in home assistant. (where you can could change its name etc.)

![unique_id](https://github.com/user-attachments/assets/50cdc415-01b0-4f52-acb3-e7b57e4ff874)

**Comment by bamirb** [comment]
You're correct. the entity doesn't have a unique_id and creating an entry in the modbus YAML doesn't solve the issue.
Is there a way around it?

**Comment by t0bst4r** [comment]
Devices without unique_id are now supported.
