### ISSUE TITLE
cannot add addon URL

### ISSUE THREAD

**Issue by Wyman42** [t0bst4r/home-assistant-matter-hub#167]
Hello, On HomeAssistantOS 13.2. core: 2024.11.1 - supervisor: 2024.11.2
error message when adding the URL to add-ons repositories.
Thanks for your work ;)

![Capture d’écran 2024-11-18 111455](https://github.com/user-attachments/assets/4727f25e-0ebb-4f7e-b648-9f567539494f)

**Comment by t0bst4r** [comment]
Hello,

as stated in the readme, you need to add this url: `https://github.com/t0bst4r/home-assistant-addons`
In Home Assistant "addon repositories" do not include the project itself, but they are containers which include only configurations on how to install an addon.
