### ISSUE TITLE
Thermostat shouldn't expose Humidity cluster if null.

### ISSUE THREAD

**Issue by KipK** [t0bst4r/home-assistant-matter-hub#168]
Humidity cluster shouldn't be exposed if climate entity doesn't have it as attribute.

This is not a priority issue as GH app is bugged and won't always displays it, But Google speakers will says there's 0% humidity in the related room.

**Comment by KipK** [comment]
I think this is for humidity setpoint for climate devices ain't it?

**Comment by t0bst4r** [comment]
Yes, seems like that, but having the humidity `null` could also mean it is currently unavailable but will be available later.
Is it reliable to check if its not set at all (`undefined` in JavaScript) ?
