### ISSUE TITLE
Thermostat jumps temp up and down when connected to Google Home

### ISSUE THREAD

**Issue by radurambet** [t0bst4r/home-assistant-matter-hub#170]
I am using some thermostats , actually they are TRVs for heating .

I have them connected trough Zigbee MQTT ( I tried tuya integration also same result). There are 2 bugs that makes this integration impossible to use:

1) When connected directly to the thermostat (climate) entity they are detected cooling _heating entity . That are not detected bay any other integration or thermostat 
2) When using BetterThermostat iuntegration that creates a virtual entity it is indeed detected as heating (dont know why exactly) but that le's say solves the first problem .

The biggest problem is that in both cases when connected to Google home immediatley after some adjustments are done in gooogle interface the matter-hub addon starts to move temperature up and down by 2-3 degrees every second . This stops if I shut down the addon or restart it.

I think this should be investigated as I could replicate this behaviour with any thermostat (TRV) that I have wether is connected trough Zigbee MQTT or Tuya integration .

I have attached logfiles with both thermostats (virtual) and actual connected one.
[LOG-Matter2-491eb00d_hamh_2024-11-18T17-59-34.168Z.log](https://github.com/user-attachments/files/17804583/LOG-Matter2-491eb00d_hamh_2024-11-18T17-59-34.168Z.log)
[LOG-Matter-491eb00d_hamh_2024-11-18T17-38-22.249Z.log](https://github.com/user-attachments/files/17804585/LOG-Matter-491eb00d_hamh_2024-11-18T17-38-22.249Z.log)

![Capture](https://github.com/user-attachments/assets/14bb9529-949b-4664-a191-ddff6160368f)

This should not be seen as climate: heat_cool entity but just as a heat entity. 

![Untitled](https://github.com/user-attachments/assets/bee3dd22-a58a-4abd-8fb2-62a692067c2d)

**Comment by t0bst4r** [comment]
The first problem is related to auto-mode.
Matter's definition of "auto" mode has some overlap with home assistant's definition of "auto" mode, but they are not the same. If i activate auto mode for matter, i am forced to enable cooling, too. I am still not sure, what would be the correct way to solve this.

The second problem looks really strange. The screenshot from home assistant looks like you have it setup HA to use Celsius. Do you have Google Home configured to use Fahrenheit?

**Comment by t0bst4r** [comment]
does this still happen with the latest version?

**Comment by radurambet** [comment]
> does this still happen with the latest version?

Not anymore witg Alpha 51. Sill some issues but mostly fixed and usable now !
Thank you !
