### ISSUE TITLE
Clarification Needed on IPv6 Requirements in Documentation

### ISSUE THREAD

**Issue by simeononsecurity** [t0bst4r/home-assistant-matter-hub#171]
The current documentation for the Home Assistant Matter Hub should more explicitly clarify the requirement for IPv6. Specifically, it should state that IPv6 must be enabled locally on the host machine and the local network and that it is necessary for Matter communication. However, there is no requirement for an IPv6-enabled WAN connection. This clarification would be helpful as many users may have local IPv6 disabled as a security best practice, or their network hardware may not support IPv6 locally, even if it is optimal from a future-proofing perspective.

Additionally, while the documentation implies that IPv4 is optional but supported, it would be beneficial to elaborate on how IPv4 can be used and what limitations might exist if IPv4 is enabled but IPv6 remains disabled. Currently, from my testing, IPv6 is mandatory. If there are specific configurations needed for IPv4-only setups, adding those details would be greatly appreciated.

Thank you for considering these enhancements to make the documentation clearer and more user-friendly!

**Comment by pixelion8** [comment]
Hi,
I am trying to check my local network settings because for me everything went fine until the step to Link to my google home. All of my entities showed up and all but grey and marked offline. I was trying to check my local network and I want to ask if you add to activate DHCPV6 and DNSv6. Also I have two options : a firewall for ipv6 and a firewall on  secondary prefixes. Should I turn them down ?

**Comment by Apollon77** [comment]
Maybe linking to https://github.com/project-chip/matter.js/blob/main/docs/TROUBLESHOOTING.md#matter-and-ipv6 could be an idea?

**Comment by simeononsecurity** [comment]
> Maybe linking to https://github.com/project-chip/matter.js/blob/main/docs/TROUBLESHOOTING.md#matter-and-ipv6 could be an idea?

Linking to 3rd party documents for a project of this scale, is that really advisable?

Additionally that documentation is already linked in the "documentation" for this project. 
The page linked, mentions
> Matter requires IPv6, but optionally also allows IPv4. If you have issues with pairing, please check if your network allows IPv6 traffic.

If it optionally allows IPv4, why doesn't it work on IPv4. I tried Google Home, Alexa, HomeKit, and Smart Things and none of them worked until I enabled IPv6. Which brings the questions.
- If there is some configuration on our end that enables IPv4, what is it and how can we enable it?
- If there is a strict requirement on the services we're pairing with for IPv6 and we can't enable IPv4 functionality on our own, then where is the documentation specifically stating that?

**Comment by simeononsecurity** [comment]
> Hi, I am trying to check my local network settings because for me everything went fine until the step to Link to my google home. All of my entities showed up and all but grey and marked offline. I was trying to check my local network and I want to ask if you add to activate DHCPV6 and DNSv6 (personalisation). Also I have two options : a firewall for ipv6 and a firewall on secondary prefixes. Should I turn them down ?

It's possible that a firewall setting is contributing to the issue. However, in my experience, pairing typically fails altogether if IPv6 isn't enabled. Since you've managed to get past the pairing step and are encountering problems with your entities showing as offline, it seems likely that you are facing a different issue.

I could be mistaken, but based on what you've described, your situation may align more closely with the problem discussed in this issue: https://github.com/t0bst4r/home-assistant-matter-hub/issues/163. It might be worth monitoring that thread for any updates or solutions.

**Comment by Apollon77** [comment]
@simeononsecurity 
> However, I have some concerns about relying on external documentation for a project of this scope.

Hm ... matter.js is the base project used by this project to offer all matter related functionality ... so when matter.js would disappear then missing documentation is the smallest problem this project would have ;-) 

For "failing with IPv6" I need to say that basically (at least last time i checked) only Google Home was not working without IPv6 ... So Apple and Alexa were able to do also with IPv4, but truely this is "edge case" and "can break anytime".

So said sort: if you have proposals on how to improve the pages (also in matter.js) I am happy about Pull Requests with changes you consider helpful. Thank you

**Comment by simeononsecurity** [comment]
> @simeononsecurity
> 
> > However, I have some concerns about relying on external documentation for a project of this scope.
> 
> Hm ... matter.js is the base project used by this project to offer all matter related functionality ... so when matter.js would disappear then missing documentation is the smallest problem this project would have ;-)
> 
> For "failing with IPv6" I need to say that basically (at least last time i checked) only Google Home was not working without IPv6 ... So Apple and Alexa were able to do also with IPv4, but truely this is "edge case" and "can break anytime".
> 
> So said sort: if you have proposals on how to improve the pages (also in matter.js) I am happy about Pull Requests with changes you consider helpful. Thank you

That being said, if a major component of a project has limitations then those should be documented in addition to this project. 

I spent a good deal of time testing, may be a edge case sure. But I've tested in two entirely separate network environments now. Each with Apple HomeKit, Google Home, Amazon Alexa, and Samsung SmartThings. I was unable to even get past the pairing stage without IPv6 enabled. 

I'd be glad to open a PR on either or both project(s) if I understood the problem at more than a high level.
Sounds like IPv4 being optional is something controlled on the service side and not on our side. If that is the case, then we should just document that.  

As far as the matter.js docs, I'd only change a line or two. Barely worthy of a PR, if at all. Assuming I understand the problem now, I'd be glad to submit some suggested changes.

As far as this project goes, I'd probably put in the actual readme that IPv6 is required in almost all cases.

**Comment by Apollon77** [comment]
Yes yes Matter-wise ipb6 is "the way to go" ... IPv4 might work but can be turned off by device updates or anything anytime. SO I would only rely on IPv6 for matter to be on safe side.

**Comment by t0bst4r** [comment]
I have added some comments in the "documentation" for now.

- https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#prerequisites
- https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md

Feel free to raise a PR to further improve it.
