### ISSUE TITLE
exclude entity via a label not working?

### ISSUE THREAD

**Issue by Rolfgithub2** [t0bst4r/home-assistant-matter-hub#176]
Hi,

Nice peace of software you have made!!

I want to use a label to **exclude** devices or entities. 
I have labeled the entity but this didn't work, so I labeled the device as well, but it just doesn't seem to work.
![Screenshot 2024-11-21 at 16 14 36](https://github.com/user-attachments/assets/e697079b-655a-48f7-bc88-85fa8f51814f)

I checked the name in dev-tools
![Screenshot 2024-11-21 at 16 00 45](https://github.com/user-attachments/assets/880ff0d7-3a85-41a4-9b0d-c2ae2ee98135)
I have excluded it in the config of the Bridge :

    "exclude": [
     
      {
        "type": "label",
        "value": "nomatter"
      },
      
 But whatever I try, it is still being exposed:
![Screenshot 2024-11-21 at 16 26 08](https://github.com/user-attachments/assets/96fbf10a-4a4d-4ac8-9e67-41a1c12437d1)

I can exclude it when I use a pattern instead of a label. 
But with a label I can simplify the config and manage the exclusions in HA.

Is this a bug?
Or am I doing something wrong??

_Originally posted by @Rolfgithub2 in https://github.com/t0bst4r/home-assistant-matter-hub/issues/51#issuecomment-2491515910_

**Comment by t0bst4r** [comment]
You need to add the label to the entity, not the device.
Additionally you need to restart the addon after doing changes to entities (e.g. adding a label).

**Comment by Rolfgithub2** [comment]
Thank You!
restarting the addon did the trick.
its working fine now.
