### ISSUE TITLE
Filtering to include just a label not picking up any devices.

### ISSUE THREAD

**Issue by Absoblogginlutely** [t0bst4r/home-assistant-matter-hub#179]
Bridge version [3.0.0-alpha.36] running in a docker container.
Configuration is set to only include the label 2Alexa
I have multiple devices tagged with the label but none are discovered in the hub.
I've restarted the hub and Home Assistant 
Image shows config, entities and template that all match.
![image](https://github.com/user-attachments/assets/eb89f022-66a1-482a-ae2e-466427b05fae)
I'm not seeing any logs show up in the container even though I have logging set to debug, just the json files in the home-assistant-matter-hub directory.

`docker@docker:~/containers/matter-hub $ cat docker-compose.yml
version: '3.7'

services:
  matterbridge:
    image: ghcr.io/t0bst4r/home-assistant-matter-hub:latest
    restart: unless-stopped
    network_mode: host
    environment:
      HAMH_HOME_ASSISTANT_URL: "http://HomeAssistant.lan:8123/"
      HAMH_HOME_ASSISTANT_ACCESS_TOKEN: "eyJ<snip>xU"
      HAMH_LOG_LEVEL: "debug"
      HAMH_WEB_PORT: 8482
    volumes:
      - $PWD/home-assistant-matter-hub:/data`

**Comment by Marc--** [comment]
Hi there,
Just installed yesterday on HAOS (addon) and i've the same problem.
matterbridge linked with GoogleHome without issue, but no devices found.

The only problem i'm sure of is that the time is wrong in the addon log : there is a -1h offset with real time (timezone setting ?)

![2024-11-22 12_53_59-Home-Assistant-Matter-Hub](https://github.com/user-attachments/assets/700e0c9f-1810-4633-9dc4-972f6a545c89)
![2024-11-22 12_57_30-Paramètres – Home Assistant](https://github.com/user-attachments/assets/f74a6e70-8d5f-48d6-9bd6-cf086a825568)

[491eb00d_hamh_2024-11-22T11-54-36.415Z.log](https://github.com/user-attachments/files/17869724/491eb00d_hamh_2024-11-22T11-54-36.415Z.log)

**Comment by t0bst4r** [comment]
First of all, when adding or removing labels from entities you need to restart the addon to be able to detect those changes.

Second, as you can see with the `{{ labels() }}` template, the label is called `2alexa` and not `2Alexa`. This is case sensitive.

**Comment by Marc--** [comment]
Hi there,
Just installed yesterday on HAOS (addon) and i think i have the same problem.

matterbridge linked with GoogleHome without issue, but no devices found. First i added the label on "devices", wich is wrong. Then i try on "entities", but without luck. I double check the name of the label, restart the addon, and the whole server too.

The only problem i'm sure of is that the time is wrong in the addon log : there is a -1h offset with real time (timezone setting ?)

![2024-11-22 12_53_59-Home-Assistant-Matter-Hub](https://github.com/user-attachments/assets/e3fae7f4-09b1-4be0-a6a6-71c3b1212f30)
![2024-11-22 14_53_48-Paramètres – Home Assistant](https://github.com/user-attachments/assets/7ee38bbf-9e22-4b40-9db1-6539cec1d2ea)
[491eb00d_hamh_2024-11-22T13-55-20.736Z.log](https://github.com/user-attachments/files/17871197/491eb00d_hamh_2024-11-22T13-55-20.736Z.log)

**Comment by t0bst4r** [comment]
The time issue is not an issue. The "Z" at the end is indicating, that its UTC.

I assume the label's technical name is not "GoogleAssistant".
Please go to HA -> Dev Tools -> Templates and paste `{{ labels() }}`
You'll see a list of all available labels and how they are written.

> [!NOTE]
> after adding / removing a label to an entity, you need to restart the addon to take effect.

**Comment by Marc--** [comment]
Ok thank you and really sorry... i've installed HA only 2 weeks ago, comming from a small French solution (Jeedom).

The label is in fact : "matterbridge", event if it shows "GoogleAssistant" . I don't (yet) understant why, but  it's working. Thankls so much for taking time to respond. I'll buy you a coffe for the trouble !

Regards,
Marc

**Comment by t0bst4r** [comment]
> The label is in fact : "matterbridge", event if it shows "GoogleAssistant" . I don't (yet) understant why, but it's working. Thankls so much for taking time to respond. I'll buy you a coffe for the trouble

No problem, this is very strange... Did you create it as “matterbridge" First and then renamed it?

**Comment by Marc--** [comment]
Ho, i think you are right ! First time, i called it matterbridge, and set the labels on devices. I messed up with QR code... and then re-create it, named it differently and read an issue where you explain labels should be set on entities... and then here i am.

So maybe renaming was the problem.

**Comment by Absoblogginlutely** [comment]
> Second, as you can see with the `{{ labels() }}` template, the label is called `2alexa` and not `2Alexa`. This is case sensitive.

I should have spotted it was case sensitive. Updated and restarted the docker container and sure enough it worked. Thanks for  the quick response!

Confirming this can be closed.
