### ISSUE TITLE
Not getting notification to update the addon to 3.0.0 alpha 37 or 38

### ISSUE THREAD

**Issue by datvista** [t0bst4r/home-assistant-matter-hub#188]
My current version is 3.0.0 alpha 36, why am I not getting notification to update the addon to 3.0.0 alpha 37 or 38?

**Comment by t0bst4r** [comment]
Addon version 37 was broken, so i deleted it before anyone installed it.
Version 38 was just released some minutes ago - Home Assistant doesn't check updates every second, but on a regular basis. Every several minutes - i dont know the exact schedule.

**Comment by datvista** [comment]
Thank you
