### ISSUE TITLE
3.0.0-alpha.38 caused re-inclusion of all devices

### ISSUE THREAD

**Issue by DJBenson** [t0bst4r/home-assistant-matter-hub#189]
Just installed 3.0.0-alpha.38 and been spammed with a hundred notifications from the Alexa app saying new devices found. It's also reset my Apple Home app.

First update I've installed which has done this.

![image](https://github.com/user-attachments/assets/fd441b3c-d114-4ad4-8771-30b160c44f49)

**Comment by KipK** [comment]
Adding to this one, when it happens each device threw this in console ( with different number ) 

[ 2024-11-23T14:31:10.068Z ] [ WARN  ] [ matter.js / EndpointStoreService                   ]: Stored number 24 is already allocated to another endpoint, ignoring

**Comment by t0bst4r** [comment]
Yes, this is a bug related to the latest alpha version of `matter.js`.
I am currently reverting that upgrade and release immediately.

Unfortunately i cannot revert that those devices already changed. Sorry for that, but maybe it helps, that i am also affected 😀

**Comment by t0bst4r** [comment]
One more hint for everyone who has this bug. it happens everytime the app restarts 😀

**Comment by DJBenson** [comment]
Whoops! 😄 

Oh well, we all know the risks of running pre-release software 😉

**Comment by t0bst4r** [comment]
even worse - somehow the last release is broken too.
please wait upgrading until i write a message here

**Comment by t0bst4r** [comment]
should be back working with 40
