### ISSUE TITLE
3.0.0 alpha 39 cannot start

### ISSUE THREAD

**Issue by datvista** [t0bst4r/home-assistant-matter-hub#191]
![Screenshot_20241123-224755](https://github.com/user-attachments/assets/ebc1e296-6cb9-4302-b83b-ec43db0256fb)

**Comment by datvista** [comment]
[logs-5.txt](https://github.com/user-attachments/files/17880366/logs-5.txt)

**Comment by t0bst4r** [comment]
should be fixed with 40
