### ISSUE TITLE
When restarting, the Names of devices in the Alexa App will be reset

### ISSUE THREAD

**Issue by drBeam** [t0bst4r/home-assistant-matter-hub#192]
Awesome project, i just installed it and i'm pretty happy with it.

However i have the problem that the names of devices will be changed back to the names assigned in home assistant. For example i have a smart plug called "living room TV" in home assistant that i want to name just "TV" in alexa. However, if i restart the bridge, the name is "living room TV" after that and the group i assigned in the alexa app is gone. On Homekit this is no issue, the names and rooms persist after a restart of HAMH. 
Is there a way to fix this?

**Comment by t0bst4r** [comment]
Which version of the addon are you currently running?
There was a bug that caused Alexa to find all devices as "new devices" everytime the addon restarts - this should be fixed with the latest version.

**Comment by DJBenson** [comment]
I'm on alpha40 and my Apple Home lost all its customisations again.

**Comment by drBeam** [comment]
I‘m running Alpha38. I will test it with 40 tomorrow and let you know the results. :)

**Comment by drBeam** [comment]
Just checked it, seems to be fixed in Alpha40. Amazing!
