### ISSUE TITLE
[Enhancement] Support for Buttons

### ISSUE THREAD

**Issue by Silther** [t0bst4r/home-assistant-matter-hub#195]
Please add support fur buttons.
I currently use the addon for starting an my home assistant dashboard cast to my google nest hub. Which works with input-booleans but buttons would be nicer

**Comment by t0bst4r** [comment]
Can you provide the attributes and state of an button entity?
(HA -> Dev Tools -> State -> Search for your button)

**Comment by t0bst4r** [comment]
Okay, so buttons don't have an "on" or "off" state.
How would you suggest implementing them? I assume it's not a sensor device, because you want to press it from GH or alexa, right?

We could simulate an "on / off" unit, but we won't be able to determine an "on" or "off" state.

**Comment by t0bst4r** [comment]
> I should uploud a new photo as it has a state once you press the button, looks like a timestamp when it was pressed.

Yes i have tested this with a helper, too. No more screenshot needed.

> But isn't there already an official matter implementation?

I couldn't find one. But maybe i'm just stupid 😀

**Comment by jesusgcas** [comment]
This would be very useful to control IR devices. Thanks

**Comment by jesusvallejo** [comment]
Agree, i solved it with a switch that automatically turns itself off after 3 seconds, so effectively its a push button. Nevertheless it would be better to have a more correct implementation.

**Comment by t0bst4r** [comment]
I've had a look at generic Switch devices in matter in combination with Alexa.

It seems they are represented as a "remote control" in Alexa. And they cannot be triggered from Alexa. They can only be used to trigger an Alexa routine.

Therefore if you want to trigger an input button from alexa / GH etc. we need something different.
I used a on-off plugin unit instead. Of course those buttons can never be "on", so i changed them to immediately turn off, after they turned on. The only thing is, that most matter controllers do "optimistic updates" and then refresh a bit delayed. This means that you can turn it "On" to trigger the input_button. Then it takes about 2-3 seconds until Alexa is notified that the button is "off" again.

**Comment by t0bst4r** [comment]
This will be included in the next release later today.

**Comment by jesusgcas** [comment]
Still not released right? I tried but input buttons are not recognized. Thanks

**Comment by pr8x** [comment]
It's unfortunate that Alexa doesn't allow triggering generic switches... It seems like such a basic thing.

I tested the new input button support, but it doesn't appear to be working properly with Alexa. Created a simple automation that triggers just fine via HA, but the Alexa switch doesn't have any effect.

**Comment by jesusgcas** [comment]
I tested it with Google home. On Google home you press it and after a few
seconds turns it off as you said but nothing gets registered on home
assistant. Only appears in logbook if you press it on home assistant
