### ISSUE TITLE
Can't start the Home Assistant Addon

### ISSUE THREAD

**Issue by gubas** [t0bst4r/home-assistant-matter-hub#2]
![image](https://github.com/user-attachments/assets/b7866b49-4e9f-4c6e-b24a-70db1901d225)
![image](https://github.com/user-attachments/assets/f1bda9f3-cb0d-46f7-a4b5-9c545f199f73)
Sorry but i think there is a problem with configuration ?

**Comment by t0bst4r** [comment]
still having some bugs in the addon. please wait 😀

**Comment by gubas** [comment]
Oh sorry about that :D thanks for the work

**Comment by t0bst4r** [comment]
This should be fixed now with the newest version.
