### ISSUE TITLE
Unhandled error detected: Cannot read properties of undefined (reading 'attributes')

### ISSUE THREAD

**Issue by truongbber** [t0bst4r/home-assistant-matter-hub#20]
When adding lights, switches... an error will appear causing the container to collapse.
![Ảnh chụp màn hình 2024-10-29 042736](https://github.com/user-attachments/assets/88c4b226-0127-477d-abb4-3fc00961da8c)

**Comment by t0bst4r** [comment]
Yep, that’s the same problem as in #11
