### ISSUE TITLE
[BUG] Filter: type label faulty

### ISSUE THREAD

**Issue by Dr4g0nM4st3r** [t0bst4r/home-assistant-matter-hub#200]
If I assign a label “matter” in HomeAssistant and use this filter in Matter Hub, then it works. 

However, filters that contain a capital letter in HomeAssistant and also in Matter hub are faulty. 

As far as I have been able to reproduce this, the labels are only transferred from HomeAssistant in lower case. 
I know that a label is written with only one t, I created this label with a capital M in HomeAssistant.

Example:

HA: matter
MH: matter
- Works

HA: Mater
MH: Mater
- Does not work

HA: Mater
MH: mater
- Works

![image](https://github.com/user-attachments/assets/3e61d1a7-068d-4bfe-846b-474e3de7e0fe)

**Comment by t0bst4r** [comment]
Yes it is, and we cannot do anything about it. That's how home assistant transfers the label info.
