### ISSUE TITLE
[Enhancement] Support for input_boolean, scene, automation, script

### ISSUE THREAD

**Issue by t0bst4r** [t0bst4r/home-assistant-matter-hub#21]
I forgot about those and need to re-add them.

**Comment by joacim69** [comment]
Yay, now Input_booleans work with alpha 10 :-)

**Comment by pana800** [comment]
have anyone tried and been successful with "label" in filter? I could not have it works.

**Comment by DJBenson** [comment]
> have anyone tried and been successful with "label" in filter? I could not have it works.

This is how I'm selectively adding devices to the bridge - I have my bridge set to look for devices with the label "Matter" and only devices tagged as such in Home Assistant are surfaced - works brilliantly.

**Comment by t0bst4r** [comment]
> have anyone tried and been successful with "label" in filter? I could not have it works.

Make sure to use the slug of the label and not its name. Having a label called "My Matter Devices" probably leads to a slug "my_matter_devices".

if you want to check the label, oben the developer settings in home assistant and go to "templates". Paste in the following:
```
{{ labels() }}
```
