### ISSUE TITLE
Google Home Color Issue

### ISSUE THREAD

**Issue by GangsterStefan** [t0bst4r/home-assistant-matter-hub#210]
Whenever I tell the Google Assistant to change the color of my IKEA light bulbs, the Google Assistant tells me the lights bulbs aren't available, but the lights still change to the correct color.

I did not experience this issue when having these lights connected to the earlier home-assistant-matter-bridge version.

Everything else is working as expected, turning the lights on/off does not give this error, changing brightness is also working properly..

**Comment by t0bst4r** [comment]
This is related to #208 and will be fixed today or tomorrow 🙂
