### ISSUE TITLE
[Bug]  alpha43 All devices included again!

### ISSUE THREAD

**Issue by DJBenson** [t0bst4r/home-assistant-matter-hub#214]
It's happened again...all devices rediscovered 😞

![image](https://github.com/user-attachments/assets/dad1b894-5ffe-46f4-a878-b5c3c7f72bbe)

**Comment by t0bst4r** [comment]
Interesting. It didn’t happen for me… 
I’ll try to reproduce

**Comment by t0bst4r** [comment]
Okay i got this, too, BUT only once.
There was a bugfix for that in matter.js, so I'd assume that it needed to re-initialize once and then i'll work.

Can you verify if that happens again after rebooting?

**Comment by t0bst4r** [comment]
Ok, I think I got it. it happens everytime when restarting the bridge (not the app). 
E.g. when updating its config.

**Comment by DJBenson** [comment]
Yeah I noticed it because I enabled the new media player flags and on restart I got the dreaded flood of notifications. I really enjoy putting 90+ devices in their rooms each time it happens 😛

**Comment by t0bst4r** [comment]
I've built a fix for that (proper "update bridge" flow), but found another edge case, where this can happen:

- As long as the **app/addon** is not **restarted**, it will work.
- But when changing the bridge configuration to include more or less entities, the endpoint-ids are not properly stored in the file system anymore. Therefore some devices may randomly get a new endpoint-id.

I am working on a fix/workaround for that as well.
