### ISSUE TITLE
[Feature Request] Docker Secrets Support

### ISSUE THREAD

**Issue by HeyItsJono** [t0bst4r/home-assistant-matter-hub#218]
Since matter hub requires a long-lived HA access token, I was wondering if you might support secrets for the docker implementation.

**Comment by t0bst4r** [comment]
You can use the `config` file option where you can specify a file path which includes the app config:
- either specify `--config=/run/secrets/MY_SECRET` as command line option, or
- Set it as env variable `HAMH_CONFIG=/run/secrets/MY_SECRET`

The file needs to have a json structure matching the config. Please have a look at the readme (`configuration` section).

additionally, env variables, config file and command line options are merged. So the config file could only include the access token and the rest can be specified as env or cli

**Comment by HeyItsJono** [comment]
Thank you for the swift reply. I'm still struggling a little unfortunately.
I've done  the following:
* Create a secret: SECRET with contents:
`{"home-assistant-access-token":"**TOKEN**"}`
* Specified HAMH_CONFIG=/run/secrets/SECRET

I can see from inspecting the container environment that HAMH_CONFIG is set to /run/secrets/SECRET successfully, but it doesn't seem to be pulling the token from the secrets file. The readme seems to suggest my structure is fine though (Kebab-case).

**Comment by t0bst4r** [comment]
It seems to be the exact same error as #232
