### ISSUE TITLE
WebUI failed JSON parse error after update to 3.0.0-alpha.44

### ISSUE THREAD

**Issue by FrColin** [t0bst4r/home-assistant-matter-hub#219]
after update to 3.0.0-alpha.44
web interface display error "JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**Comment by t0bst4r** [comment]
Oh yes that’s interesting. It didn’t break for my local dev environment, but it did on my home assistant, too. At least it’s just the ui. Bridge itself should still be running

**Comment by TheLushMeadow** [comment]
I just installed this addon and have the same problem. Every time I want to add a bridge this message comes and it prevents me from adding on :(

**Comment by t0bst4r** [comment]
should be fixed with `alpha.45`
