### ISSUE TITLE
it is possible to view all discovered accessories and select?

### ISSUE THREAD

**Issue by platini76** [t0bst4r/home-assistant-matter-hub#231]
hello I see that the configuration of enabled and disabled accessories is mandatory seems.
it is not possible to have all accessories read and then only select wich I want to activate?
thanks for your precious work

**Comment by t0bst4r** [comment]
no, but I'd recommend using a label in home assistant.
So include/exclude filter would only include something like `type = label, value = matterhub`.
Then you can simple add entities by attach the label in home assistant to it.

One hint: home-assistant-matter-hub does not know about changed entities / labels immediately. you need to "reload" the bridge, by editing and saving without changes. - i'll probably add a button for that in the future

**Comment by platini76** [comment]
this is a very good solution but it is not simpliest to add a check in case of activation directly on the list of available sensors on matterhub?
