### ISSUE TITLE
Application title to long for sidebar

### ISSUE THREAD

**Issue by lone-baggie** [t0bst4r/home-assistant-matter-hub#240]
Very minor issue . Appliction name looks  too long for side bar

![image](https://github.com/user-attachments/assets/43ebe92d-963b-4779-ad6b-0cea973b480f)

**Comment by t0bst4r** [comment]
Yes, I already changed it and added an icon, too.
But it seems HA doesn’t refresh it immediately. 
I‘d wait for the next update and see if it takes effect.

**Comment by lone-baggie** [comment]
Did a rebuild and reboot  :)

![image](https://github.com/user-attachments/assets/5fd5c801-2ff1-40c4-8985-e51e9dcf3951)

All good

**Comment by thor9898** [comment]
I was going to open an issue but i think it's a too silly  problem to open a new issue so i could use this one. It seems so annoying to me to have the smarthings icon on the sidebar and more when (i think) matter icon is available.

I also wanted to thank the creator and contributors for this project as it solved a lot of headaches  I had with all my DIY devices.
