### ISSUE TITLE
Filter on label not working

### ISSUE THREAD

**Issue by istvanSA** [t0bst4r/home-assistant-matter-hub#243]
If i add devices to the hub with "domain " = "light" all my lights get added but if i use a label the one device that i labeled doesnt show up

**Comment by Biohospitalix** [comment]
It works for me without any problem. But you have to put label on entities, not on group or on devices

**Comment by Biohospitalix** [comment]
Try to put il also on devices. I remember it was on entities but I haven't my config in front of me

**Comment by GiacomoST** [comment]
J try. It doesnt show up

**Comment by HeyItsJono** [comment]
Wasn't working for me on devices, did work once I added labels to entities.

**Comment by istvanSA** [comment]
It is very strange but my label is GoogleHome that doesnt work if i dont change my label but  change it to googlehome in the addon ( so without caps) it works inatantly

**Comment by HeyItsJono** [comment]
> It is very strange but my label is GoogleHome that doesnt work if i dont change my label but change it to googlehome in the addon ( so without caps) it works inatantly

You have to use the slug of the label. To get slugs of your labels, in Home Assistant -> Developer Tools -> Template and paste in the following template: `{{labels()}}`. The box to the right will display the slugs of your labels, use those in Matter Hub.

![image](https://github.com/user-attachments/assets/e846a3c7-19a0-4a5e-8211-b67990930835)

**Comment by GiacomoST** [comment]
Yes now it work

**Comment by t0bst4r** [comment]
> > It is very strange but my label is GoogleHome that doesnt work if i dont change my label but change it to googlehome in the addon ( so without caps) it works inatantly
> 
> You have to use the slug of the label. To get slugs of your labels, in Home Assistant -> Developer Tools -> Template and paste in the following template: `{{labels()}}`. The box to the right will display the slugs of your labels, use those in Matter Hub.
> 
> ![image](https://private-user-images.githubusercontent.com/4620093/391843319-e846a3c7-19a0-4a5e-8211-b67990930835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTMxMDgsIm5iZiI6MTczMzIxMjgwOCwicGF0aCI6Ii80NjIwMDkzLzM5MTg0MzMxOS1lODQ2YTNjNy0xOWEwLTRhNWUtODIxMS1iNjc5OTA5MzA4MzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMDgwMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRlZDkwYTVjMzNjNzIyNjAyMGFlNDdjMmJhOTQyZWJmNDQzMjkxYTk4NjZiMDY5ZDNkZjBmMDQ5MGNjMTA4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Bxudfi_OyNIu2q0VY-6If7KaEvbgxWmbhsdqU-qMJHs)

What theme are you using for HA?
Looks better than mine 😀

**Comment by HeyItsJono** [comment]
> @HeyItsJono 
> > 
> > ![image](https://private-user-images.githubusercontent.com/4620093/391843319-e846a3c7-19a0-4a5e-8211-b67990930835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTMxMDgsIm5iZiI6MTczMzIxMjgwOCwicGF0aCI6Ii80NjIwMDkzLzM5MTg0MzMxOS1lODQ2YTNjNy0xOWEwLTRhNWUtODIxMS1iNjc5OTA5MzA4MzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMDgwMDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRlZDkwYTVjMzNjNzIyNjAyMGFlNDdjMmJhOTQyZWJmNDQzMjkxYTk4NjZiMDY5ZDNkZjBmMDQ5MGNjMTA4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Bxudfi_OyNIu2q0VY-6If7KaEvbgxWmbhsdqU-qMJHs)
> 
> What theme are you using for HA?
> Looks better than mine 😀 

Catpuccin Frappe I think, get it via HACS :)

**Comment by istvanSA** [comment]
> > It is very strange but my label is GoogleHome that doesnt work if i dont change my label but change it to googlehome in the addon ( so without caps) it works inatantly
> 
> You have to use the slug of the label. To get slugs of your labels, in Home Assistant -> Developer Tools -> Template and paste in the following template: `{{labels()}}`. The box to the right will display the slugs of your labels, use those in Matter Hub.
> 
> ![image](https://private-user-images.githubusercontent.com/4620093/391843319-e846a3c7-19a0-4a5e-8211-b67990930835.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjAxMjIsIm5iZiI6MTczMzIxOTgyMiwicGF0aCI6Ii80NjIwMDkzLzM5MTg0MzMxOS1lODQ2YTNjNy0xOWEwLTRhNWUtODIxMS1iNjc5OTA5MzA4MzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDNUMDk1NzAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQyZGEyNDMwYjYyMWFkZDExMTMyODI4NWY2YTY3ZTNiNTlkYzQ1MjU5MDFlMmE5YmM5YWUyNWI2M2Q4MTZkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.75vmtMJ4w67cxhBUmcd0ZHsmj1wKJLdLtelNjRXyiT4)

Yeah there it shows without caps so that was the issue
