### ISSUE TITLE
Duplicated instances imported by Alexa Media Player

### ISSUE THREAD

**Issue by digiolin** [t0bst4r/home-assistant-matter-hub#245]
Alexa Media Player integration allows to add devices connected via Echo devices. I was mainly using that to get the sensors from Echo devices. It has a way to detect if the devices were added via skill (this is how the core smart_home alexa integration is managed in HomeAssistant), the logic can be found here:
https://github.com/alandtse/alexa_media_player/blob/master/custom_components/alexa_media/alexa_entity.py

alexa_media_player doesn't import devices that were added to Alexa via the integration. Can you please @t0bst4r sync up with them in order to find a solution to the Issue? I opened an issue to them:

https://github.com/alandtse/alexa_media_player/issues/2709

Here an example of the Logs from alexa_media_player for a swich device:

```
{
    "applianceId": "AAA_SonarCloudService_<void>",
    "endpointTypeId": "",
    "driverIdentity": {
        "namespace": "AAA",
        "identifier": "SonarCloudService"
    },
    "manufacturerName": "TestVendor",
    "friendlyDescription": "TestVendor smart device",
    "modelName": "",
    "deviceType": "",
    "version": "0",
    "friendlyName": "Camara",
    "friendlyNameModifiedAt": 1733084691197,
    "capabilitiesModifiedAt": 1733084691197,
    "ipAddress": "",
    "port": "",
    "entityId": "<void>",
    "applianceNetworkState": {
        "reachability": "REACHABLE",
        "lastSeenAt": 1733130114179,
        "createdAt": 1733084691197,
        "lastSeenDiscoverySessionId": {
            "value": "<void>"
        }
    },
    "tags": {
        "tagNameToValueSetMap": {}
    },
    "additionalApplianceDetails": {
        "additionalApplianceDetails": {}
    },
    "firmwareVersion": "0",
    "actions": [],
    "capabilities": [
        {
            "capabilityType": "AVSInterfaceCapability",
            "type": "AlexaInterface",
            "version": "3",
            "properties": {
                "supported": [
                    {
                        "name": "powerState"
                    }
                ],
                "proactivelyReported": true,
                "retrievable": true,
                "readOnly": false
            },
            "interfaceName": "Alexa.PowerController"
        },
        {
            "capabilityType": "AVSInterfaceCapability",
            "type": "AlexaInterface",
            "version": "3",
            "properties": {
                "supported": [
                    {
                        "name": "connectivity"
                    }
                ],
                "proactivelyReported": true,
                "retrievable": true,
                "readOnly": false
            },
            "interfaceName": "Alexa.EndpointHealth"
        }
    ],
    "applianceTypes": [
        "SMARTPLUG"
    ],
    "isEnabled": true,
    "aliases": [],
    "connectedVia": "Echo Comedor",
    "alexaDeviceIdentifierList": [],
    "applianceKey": "<void>",
    "identifiers": {},
    "applianceDriverIdentity": {
        "namespace": "AAA",
        "identifier": "SonarCloudService"
    },
    "ipaddress": "",
    "applianceLambdaControlled": true,
    "mergedApplianceIds": [
        "AAA_SonarCloudService_<void>"
    ]
}
```

**Comment by t0bst4r** [comment]
I don’t think we can do anything about it in the hub. I will check why the manufacturer is "TestVendor" instead of "t0bst4r", but that‘s all I can do here…

On the other hand, I don’t think there is a clean automated way for alexa-media-player to decide which devices to exclude or include.
To solve this, there needs to be a way to tell alexa-media-player which ones to exclude.

I am closing this issue to keep track in the other issue (https://github.com/alandtse/alexa_media_player/issues/2709)

**Comment by danielbrunt57** [comment]
@t0bst4r FYI, [fix: home-assistant-matter-hub duplicated entities #2730](https://github.com/alandtse/alexa_media_player/pull/2730) with home-assistant-matter-hub 3.0.0-alpha.52 is now preventing duplication of entities by Alexa Media Player.
Thanks for changing/correcting `manufacturerName` from `TestVendor` to `t0bst4r`!
