### ISSUE TITLE
Temperature Sensor only displays in increments of 0.5°C in Google Home

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [t0bst4r/home-assistant-matter-hub#251]
In the addon's ingress page (nice that that's now implemented btw!), my temperature sensors read as follows:
![image](https://github.com/user-attachments/assets/0261659c-0799-4572-8509-b5c104149a08)
Which is in line with what Home Assistant reports. However, in the Google Home app (and thereby also when using Google Assistant), it only ever shows in increments of 0.5°C:
![Screenshot_20241203-165830](https://github.com/user-attachments/assets/0ce03b2c-fff1-4493-832e-090f9ed6ed7c)

**Comment by t0bst4r** [comment]
We are reporting the value exactly as you see it on the UI to all controllers. It seems to be google home which just displays rounded values.

**Comment by ThatBlockyPenguin** [comment]
> We are reporting the value exactly as you see it on the UI to all controllers. It seems to be google home which just displays rounded values.

Well, that's annoying. Must be yet another symptom of their poor implementation of Matter. These same sensors, when connected directly via their cloud integration to Google Home, report accurate values. Thanks for your quick response.

Closing as issue is with Google, not this addon.

**Comment by Apollon77** [comment]
I think not that is has anything to do with a "poor matter implementation" but maybe with the definitions of their understanding of Smart home devices and usage ... But yes ... should be reported to Google
