### ISSUE TITLE
3.0.0-alpha.51 TRV all enabled and wit set temp to 20ºC

### ISSUE THREAD

**Issue by digiolin** [t0bst4r/home-assistant-matter-hub#259]
Last upgrade broke all the config of my TRV ut changed it config and enabled all of them by default to 20ºC in Heat mode. I had some of them set to 35ºC and others Off. When I updated all of them changed. If I do any change in HA and restart they are again all On in 20ºC.

**Comment by t0bst4r** [comment]
Thank you for your contributions and reports regarding climate/thermostat-related issues. I've noticed that this area has become increasingly complex, with overlapping tickets and discussions. To streamline the process and ensure we address everything effectively, I’ve decided to close the existing tickets on this topic.

Instead, I’m creating a [centralized discussion](https://github.com/t0bst4r/home-assistant-matter-hub/discussions/261) where we can collectively revisit and tackle these challenges in a structured manner. Please feel free to share your insights, reproduce steps, and ideas there.
