### ISSUE TITLE
[Enhancement] Pin Protection for covers/locks

### ISSUE THREAD

**Issue by chino-lu** [t0bst4r/home-assistant-matter-hub#26]
I was wondering if it would be possible to set a pin protection like with the secure_devices_pin used in the Google Assistant Integration (https://www.home-assistant.io/integrations/google_assistant/)

Right now, the garage door is seen as a simple cover. When I tell Google to open all covers, the garage will open as well.

With this pin protection, only covers without this had been opening

**Comment by t0bst4r** [comment]
Can you add some more details how that works?
If you dont want to control it with your voice assistant couldn't you then just exclude from your bridge?

**Comment by chino-lu** [comment]
when using the part of home assistant and setting a pin, the garage door would not open. But it would give me the possibility to open the garage door when asking it. First it would ask for the pin before going ahead and open the garage door. The same would happen in the Google Home App, before beeing able to open the garage door, it would ask for the pin.

This would avoid that somebody could just shout trough your window to open the garage door.

But it seems this is not supported: https://developers.home.google.com/matter/supported-devices#door_locks
So this request can be closed

**Comment by t0bst4r** [comment]
Ah okay. Now i get it.

Alexa, by default, does not allow controlling locks. You have to open that lock in the Alexa-App and enable controlling that lock. If i remember correctly, it's also possible (**in the alexa app**) to configure a pin, which is just internally used in alexa. Matter and Home Assistant won't know about that, but alexa just don't control the lock without the pin.

Maybe you could check in Google Home if that's configurable there, too?

**Comment by thewan056** [comment]
> But it seems this is not supported: https://developers.home.google.com/matter/supported-devices#door_locks So this request can be closed

I think you are misunderstanding the documentation Google provided in your link above.

Implementing and enforcing use of a pin code is done on the matter side.

Google is mandating using a pin for remote unlocking matter connected locks (and all locks in the Google Home ecosystem really). Setting a pin for locks is not required in the matter standard, but can be enforced, which is what Google requires. If not enforced, Google Home will simply not allow remote unlocking. (Locking should still work)

Firstly your garage, and whatever else you want to remote lock/unlock needs to be a Lock/Doorlock, not a Cover which is usually used for stuff like curtains for Google to identify it as something to be able to Lock or Unlock. Second is to set _requirePINForRemoteOperation_ on the matter side and things and probably provide a place for a user to set a pin on the matter side of things. Then Google Home should function as intended regarding matter locks.

Source: Kinda vague explanation from [here](https://www.googlenestcommunity.com/t5/Smart-Home-Developer-Forum/Setting-Up-a-PIN-Code-for-Matter-Smart-Locks/m-p/604140/highlight/true#M6620)
