### ISSUE TITLE
Not able to dim lights on google nest hub

### ISSUE THREAD

**Issue by neleig** [t0bst4r/home-assistant-matter-hub#268]
Everything is working fine in the google home app on my phone, all my lights are dimmable from the app.
But my google nest hub shows all my lights as on/off and no level control.

I don't actually know if this is a HAMH issue or an issue with the google nest hub.
Log does not show any errors, but attached is the startup debug log of a bridge with only one of my lights. 
[491eb00d_hamh_2024-12-06T21-29-46.267Z.log](https://github.com/user-attachments/files/18044668/491eb00d_hamh_2024-12-06T21-29-46.267Z.log)

**Comment by neleig** [comment]
As soon as I submitted this issue the level control of the light suddenly started to work on my nest hub.
Assuming something had magically solved itself, I started another bridge with all my lights.
None of the lights had working level control, also not the one that worked previously.
Swithing back to the single light bridge also did not work anymore.

Seeing that it briefly worked for some reason I'm also starting to think it might be something in my network.
But all other functions are working just fine, except for the level control from the nest hub.

**Comment by t0bst4r** [comment]
I assume that to be an issue with google nest.
When you pair it with the google home app, the controls are there. Therefore i don't see any problem on HAMH side.
Additionally the logs show the correct initialization of levelControl cluster.

Did you try pairing the same bridge with both google home app and google nest hub?

**Comment by neleig** [comment]
Thanks for the quick answer.
My google nest hub is added in the google home app. And after that i've only paired the bridge with the google home app.
Maybe i'm missing something, but I don't think there is an option to pair the bridge directly to the google nest hub.

**Comment by marcbernis** [comment]
Hello,
First thanks for this wonderful idea and software!
I've same issue, lights (single or group) are correctly added in Google home and I can dim them from there without issue.
But Google assistant (french) always says that there is no dimmable light added to Google home.

**Comment by Moonbase59** [comment]
Quick note: I have a DimmableLight "Wohnzimmer Stehlampe" which worked a few versions before (can't remember which) using

- Alexa App
- Alexa Echo Dot (5th Gen) "Computer, Stehlampe auf 50%" ("Computer, Stehlampe to 50%")
- Google Home App
- Google Nest Mini (2nd Gen) "Hey Google, Stehlampe auf 50%"

Using 3.0.0-alpha.54, and watching both apps and HA, I now get the following:

- Alexa App – works, can dim
- Alexa Echo Dot – works, but brightness change not reflected in GH App
- Google Home App – works, light is dimmable
- Google Nest Mini – "Hey Google, Stehlampe auf 50%" results in "Entschuldige, das habe ich nicht verstanden" ("Sorry, I didn't understand that")
- Google Nest Mini – "Hey Google, Stehlampe aus" (switch off) results in light being switched off, which Alexa and HA also see.

Looks like Google Nest devices cannot dim a DimmableLight in this version.

**Comment by marcbernis** [comment]
I'm using Nest mini and so we have the same experience.  Google home ok, on
nest lights (tried multiple vendors) are not dimmable

**Comment by Apollon77** [comment]
A debug log of such a try to dim would be cool - also potentially in commparism where is works and where not

**Comment by neleig** [comment]
I don't think I will be able to create a debug log of a dim attemp that fails. The google nest hub just does not send the command because the light has no dim capability, only on/off. On the google nest hub it's easy to see right after initialization, because the UI will only show on/off for the light, or it will show the current dim level. 
But, as indicated in my previous post, I've also seen that it once worked as intended. So I tried to catch that situation in a debug log.

In the attached log I've tried the following (multiple times, with different bridges):
 - Add a bridge with one light to the google home app
 - Verify in the google home app that the light is dimmable
 - Check on the google nest hub if the light is dimmable
 - If not remove remove the bridge from the google home app and start over again.

In most of my attemps it failed and I could not control the dim level of the light from the google nest hub (google home app always works).

Around 22:35 I decided to reboot the google nest hub, and after that is suddenly worked. The google nest hub showed the dim level of the light, and I was able to control the dim level from the google nest hub (dim actions should be visible in the log file).
Around  22:45 I added a second light to the bridge, and after that both lights were not dimmable anymore. Again I tried to reboot the google nest hub, but this time it did not work.

[491eb00d_hamh_2024-12-09T22-50-55.761Z.log](https://github.com/user-attachments/files/18069170/491eb00d_hamh_2024-12-09T22-50-55.761Z.log)

I don't know if it is possible to install an older version of the addon in Home Assistant. Else it should be easy for me to test with older versions and provide the debug logs.

**Comment by marcbernis** [comment]
hello again,
Just capture a single line with device addon  (a philips dimmable bulb):

[ 2024-12-10T11:31:03.654Z ] [ INFO  ] [ Matter / Endpoint                                  ]: 93540fa34d994683a2f6e1b6ba7fd156.aggregator.light_chevet_de_la_chambre ready endpoint#: 15 type: ColorTemperatureLight (0x10c) behaviors: ✓identify ✓groups ✓onOff ✓levelControl ✓colorControl ✓bridgedDeviceBasicInformation ✓homeAssistantEntity ✓descriptor

It works pefectly on google home, while French assistant from google nest mini says " there is no dimmable light in your config, add a new one from google home". 
Strange is that color control works fine from assitant (and home).

**Comment by Moonbase59** [comment]
Here's a one-minute debug log from v3.0.0-alpha.54, for issuing the following commands (both Alexa Echo Dot and Google Nest Mini connected to the same HAMH bridge):

- "Computer, Wohnzimmer Stehlampe aus" (Alexa, works)
- "Computer, Wohnzimmer Stehlampe auf 50%" (Alexa, works)
- "Hey Google, Wohnzimmer Stehlampe aus" (Google, works)
- "Hey Google, Wohnzimmer Stehlampe auf 50%" (Google, claims it doesn't understand, no visible log entry)
- "Hey Google, Wohnzimmer Stehlampe an" (Google, works)

"Wohnzimmer Stehlampe" is an ExtendedColorLight (WLED). I also tried using a DimmableLight "Büro Stehlampe" (Espurna Dimmer), and it shows the same behaviour.

I wonder if this is a sudden Google Home/Assist issue, or maybe caused because some device tries to set a _float_ (127.5) for brightness?

Btw, setting the brightness using the GH App works, just not when using the Nest Mini.

[491eb00d_hamh_2024-12-11T17-27-12.995Z.log](https://github.com/user-attachments/files/18099971/491eb00d_hamh_2024-12-11T17-27-12.995Z.log)

**Comment by vwccvr6** [comment]
I had the same problem. After saying "hey google, sync my devices" (and waiting several minutes) i am able to dimm all lights via voice command. 
I don't know if the "sync my device" was the actual fix. 

Maybe someone can try.

**Comment by Apollon77** [comment]
Honestly ... thats then a pure google issue and has maybe even nothing to do with Matter ... so if "just" the voice assistant" do not understand you/does not find stuff it is on that side ... seems that all matter related things work

**Comment by Moonbase59** [comment]
@Apollon77: That may be so—don't know how these thingies update, so maybe some unnoticed Google bug. What nags me a little is that exactly the same command worked a few HAMH versions before.

Any suggestion for a non-Google, non-Alexa, non-HomeKit, easy-to-use Matter controller for Linux we could use to test? (Possibly without having to install dev environments like npm or the like?)

**Comment by gklank** [comment]
> Honestly ... thats then a pure google issue and has maybe even nothing to do with Matter ... so if "just" the voice assistant" do not understand you/does not find stuff it is on that side ... seems that all matter related things work

Hi,

in first hand it looks like that what you are saying is correct.

But in the other hand: with using the nabu casa cloud to GH and with the same stuff as now used in the HA-matterhub the voice assistant is working.
Also in the GH app these devices are shown as dimmable and can used in that way.

So therefore I am assuming that there is still a bit difference within the HA-matterhub which is not totally understood by GH.


Regards

Gerhard

**Comment by gklank** [comment]
sorry, just hours later, nothing done, nothing changed - it's now functioning.
Just told to GH via voice to change my light to 25% - it was functioning.

Fine - but why?


Regards

Gerhard

**Comment by Apollon77** [comment]
maybe  Google fixed the issue in they Firmware/Cloud system?

**Comment by kennylevinsen** [comment]
Yeah, seems like it. I also had this quirk appear after I had returned from a trip without anything having changed. Controls worked in the Google Home app (spoken or manual), while smart speakers failed any dimming. Removing the lights, syncing, re-adding them and syncing was what it took to fix it.

With that in mind this can probably be closed as "not our bug".
