### ISSUE TITLE
[Bug]: Climate unnecessarily converting fahrenheit

### ISSUE THREAD

**Issue by bassrock** [t0bst4r/home-assistant-matter-hub#271]
### Version

3.0.0-alpha.51

### Matter Controller

Apple Home

### Steps to reproduce

I have an Ecobee connected to HomeAssistant via the HomeKitBridge connection, I am then trying to export it via the Matter Hub add-on. When it shows up in the Home App, all the temperatures are around 162 degrees. My system currently uses fahrenheit for its units. It looks like the add on is converting the fahrenheit units into celcius

### State and attributes

hvac_modes: off, heat, cool, heat_cool 
min_temp: 45 
max_temp: 92 
fan_modes: on, auto 
friendly_name: Bedrooms 
supported_features: 395 
current_temperature: 74 
temperature: 74 
target_temp_high: null 
target_temp_low: null 
current_humidity: 38 
fan_mode: auto 
hvac_action: idle

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by DMedina559** [comment]
https://github.com/t0bst4r/home-assistant-matter-hub/discussions/261

**Comment by t0bst4r** [comment]
This will be handled as part of a larger refactoring of climates (see #261)
