### ISSUE TITLE
[Bug]: "Label" does not work as include or exclude filter

### ISSUE THREAD

**Issue by darth-hp** [t0bst4r/home-assistant-matter-hub#273]
### Version

3.0.0-alpha.52

### Matter Controller

Alexa

### Steps to reproduce

Choose any supported entity which is not already included via any filter in the matter bridge and add a label, eg "Voice". Then go to the bridge and add an include for the label "Voice". It will not appear in the list of devices.

For excluded, make certain you have a filter in place that includes devices. Then go to one entity which is included, apply a label, eg "Novoice". Go to the bridge and create an exclude filter for label "Novoice". The device will not be excluded.

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
In the background home assistant is not using the name of the label, but its "slug".
You have to use that slug for the filters.

You can find the slug by writing `{{ labels() }}` into a template (HA -> Developer tools -> Template).

**Comment by darth-hp** [comment]
I see. Basically it seems to be a lowercase version of a label if it doesn't contain other than just letters.

You can't use the list from `{{ labels() }}` for selection? Else a hint would be helpful.

**Comment by Barneybaer84** [comment]
Thanks you all. Now IT works.

**Comment by goldrapper19872504** [comment]
Bei mir geht es trz nicht

**Comment by Barneybaer84** [comment]
> Bei mir geht es trz nicht

Du darfst die Labels im Filter nur klein und ohne Umlauten schreiben. So wie es HomeAssistant vorgibt. Prüfen kannst du deine Labels unter Entwicklerwerkzeuge/Template in dem du dort am Ende {{ labels() }} einträgst. Darunter erhälst du dann die Ausgabe.

**Comment by goldrapper19872504** [comment]
![Screenshot (73)](https://github.com/user-attachments/assets/d1269ad5-514a-467e-83c4-59acd5bef8af)
![Screenshot (74)](https://github.com/user-attachments/assets/8c37a4e7-3dda-40e0-aa70-6d7554cf8cff)
![Screenshot (75)](https://github.com/user-attachments/assets/088ef918-3137-478e-86f2-53147d170458)
Geht trz nicht

**Comment by darth-hp** [comment]
Ist HA das HAOS basierend?
