### ISSUE TITLE
[Bug]: Google Home not working after update 3.0.0-alpha.53

### ISSUE THREAD

**Issue by datvista** [t0bst4r/home-assistant-matter-hub#274]
### Version

3.0.0-alpha.53

### Matter Controller

Google Home

### Steps to reproduce

Google Home not working after update 3.0.0-alpha.53
[logs-6.txt](https://github.com/user-attachments/files/18060214/logs-6.txt)

### State and attributes

[logs-6.txt](https://github.com/user-attachments/files/18060192/logs-6.txt)

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
next release with a hot fix is in progress of being created
