### ISSUE TITLE
[Bug]: devices randomly readded to google home

### ISSUE THREAD

**Issue by KipK** [t0bst4r/home-assistant-matter-hub#278]
### Version

alpha-52-54

### Matter Controller

Google Home

### Steps to reproduce

Happened during the night yesterday and today, waking up with Google Home notification about new devices added.
All devices where removed and recognised as new ones, needing to reconfigure all of them. 
Matter Hub was not rebooted during the night.
Relevant logs posted below , there's nothing else logged thereafter, so it seems it happened after 2:20 am

### Relevant log output

```shell
[ 2024-12-10T02:20:34.062Z ] [ INFO  ] [ Matter / ServerSubscription                        ]: Error sending subscription update message (error count=1): 
[ 2024-12-10T02:20:50.218Z ] [ INFO  ] [ Matter / ServerSubscription                        ]: Error sending subscription update message (error count=1): 
[ 2024-12-10T02:20:56.249Z ] [ INFO  ] [ Matter / ServerSubscription                        ]: Error sending subscription update message (error count=2): 
[ 2024-12-10T02:21:00.284Z ] [ INFO  ] [ Matter / CaseServer                                ]: Received pairing request from udp://2a01:cb05:8f20:8aec:ac78:b9e4:f059:7953:5540
[ 2024-12-10T02:21:00.417Z ] [ INFO  ] [ Matter / CaseServer                                ]: session 40924 created with udp://2a01:xxxxxxxxxxxxxxxxxxxxxx for Fabric 00000000BF0DA1F5(index 1) and PeerNode 0000000088F90ED3 with CATs 65537
[ 2024-12-10T02:21:00.533Z ] [ INFO  ] [ Matter / InsecureSession                           ]: End insecure session insecure/3755012722899755379
[ 2024-12-10T02:21:00.985Z ] [ INFO  ] [ Matter / InteractionServer                         ]: Successfully created subscription 2964030481 for Session 40924. Updates: 0 - 30 => 31 seconds (sendInterval = 25 seconds)
[ 2024-12-10T02:21:04.729Z ] [ INFO  ] [ Matter / CaseServer                                ]: Received pairing request from udp://2a01:xxxxxxxxxxxxxxx:5540
[ 2024-12-10T02:21:05.390Z ] [ INFO  ] [ Matter / CaseServer                                ]: session 23470 created with udp://2a01:xxxxxxxxxxxxxxxxx for Fabric 00000000DA8402B0(index 1) and PeerNode 0000000088F90ED3 with CATs 65537
[ 2024-12-10T02:21:05.499Z ] [ INFO  ] [ Matter / InsecureSession                           ]: End insecure session insecure/12303254117298041709
[ 2024-12-10T02:21:06.006Z ] [ INFO  ] [ Matter / InteractionServer                         ]: Successfully created subscription 865146145 for Session 23470. Updates: 0 - 30 => 33 seconds (sendInterval = 26 seconds)
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by KipK** [comment]
Happened again tonight around 3am, same log as above. All devices removed and appearing as new devices discovered.

I wonder if matter.js 0.11.9 won't fix that, I see this commit about reconnection handling: https://github.com/project-chip/matter.js/commit/09ad57f78626862add889d8c27976539d9470d4b

**Comment by t0bst4r** [comment]
We are currently using a pre-release version of 0.11.9 (`0.11.9-alpha.0-20241208-09ad57f78`), because it fixes a bug with fans.

The commit you linked was merged (https://github.com/project-chip/matter.js/pull/1488) just **before** this pre-release version - so it should be included already. 

Maybe @Apollon77 could give a hint 🙂

**Comment by KipK** [comment]
Perhaps this is the culprit then 😉

**Comment by Apollon77** [comment]
This was just a topic for controller usage, you work as a bridge. So it is completely unrelated. In fact it is strange that devices gets re-created just because of a subscription re-establishment (probably the hub got an update or such) ... such cases usually only happen on bridge restart if the endpoint assignment is lost ... so no ideas ... but without debug log also hard to spot more

**Comment by KipK** [comment]
I've activated debug today to catch it when it'll happened again

**Comment by KipK** [comment]
Happened again tonight. There's gazillon of logs, I've tried to filter out the related part , not 100% sure it is the correct part but I think it is when it happened:


[matterbridgelog.txt](https://github.com/user-attachments/files/18107011/matterbridgelog.txt)

**Comment by Apollon77** [comment]
At least I can not spot anythng beside a resubscription hat could have caused this behavior .. especially no partLists changes

**Comment by KipK** [comment]
Since alpha-56 problem seems to be solved. Thing haven't happened for 2 days yet.  I

**Comment by t0bst4r** [comment]
In alpha 56 I've added the serial number to every device. That could definitely be related.

Let's observe it for a few days.

**Comment by KipK** [comment]
> In alpha 56 I've added the serial number to every device.

Clearly solved the issue. No problem since. 

Thanks
