### ISSUE TITLE
[Feature]: Add Feature to stop specific devices from going to Google, Apple, Alexa

### ISSUE THREAD

**Issue by rfiorenza80** [t0bst4r/home-assistant-matter-hub#283]
### Requested feature

I was hoping that you could add a tick box after Matter imports devices so that you can unselect specific devices from being sent to Google Home, Apple Homekit or Alexa. For example, WLED has multiple switches and lights if you have multiple segments, I want to be able to just send the main on/off to Google Home and ignore all the rest.

### Documentation & Issues

- [X] I have reviewed the list of [currently supported entities and their limitations](https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#5-supported-domains--device-types).
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar requests.
- [X] I have [checked](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md) if my controller is known to support the requested device type.

**Comment by juanjo-ferrero** [comment]
I think this is exactly what multiple bridges functionality is for. Just create one bridge for each ecosystem you want to use, and filter the devices you wish to make visible to each of them.

**Comment by juanjo-ferrero** [comment]
I see... I don't have any WLED devices unfortunately so I don't know what kind of entities HA adds. If you can't assign only the "Power" entity a label, what I would do is create a boolean helper and assign the "google_home" label to it (it will be exposed as a switch to GH) and remove the label from the WLED lights. After that I would sync the helper On/Off state with the lights On/Off state using a simple automation. Hope that helps.

**Comment by rfiorenza80** [comment]
Got it working using {{ labels() }} to find out how HA was storing the label. All good now.

**Comment by Moonbase59** [comment]
**Hint for others who might read this later:**

With devices that expose a lot of entities (like WLED, AWTRIX clocks, etc.), you might want to expose _only the `light.something` entity_, not the whole device. This keeps Alexa and Google Home/Assist from trying to turn on/off other devices features.

You _can_ label (and thus expose) selected other features for a device, like maybe WLED's "Nightlight" feature, or AWRTRIX' matrix or indicator "lights".
