### ISSUE TITLE
[Bug]: No devices found when working with labels

### ISSUE THREAD

**Issue by r77s** [t0bst4r/home-assistant-matter-hub#296]
### Version

 3.0.0-alpha.54

### Matter Controller

Alexa

### Steps to reproduce

Added a label:
![image](https://github.com/user-attachments/assets/ba690c26-cd7e-49b6-8781-bfde9237f74b)
Use Name: MatterHub
Add this label to other device.
Use this label in the matter hub with "matterhub" lowercase.

When I try this on this way, no device will be found.
When I do the same with pattern, the devices will be found.

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by hipp0o** [comment]
I confirm

**Comment by mgraebi** [comment]
You must labeling the entities, not devices

**Comment by r77s** [comment]
You are write. Sorry

**Comment by hipp0o** [comment]
> You must labeling the entities, not devices
nope, right from the start I labeled entities - still doesn't work.
