### ISSUE TITLE
[Bug]: remote unlock of HmIP-DLD via Google Home voice command not functioning

### ISSUE THREAD

**Issue by gklank** [t0bst4r/home-assistant-matter-hub#300]
### Version

3.0.0-alpha.54

### Matter Controller

Google Home

### Steps to reproduce

- Matterhub setup with label = "matterhub"
- assign label to HmIP-DLD
- restarting matterhub
- synchronize devices in Google Home

### State and attributes

- task: "saying: hey google, unlock garage door"
- answer: garage door can not be unlocked remotely

--> HmIP-DLD has no PIN
--> in HA I found the entity detail with the line "standard code" - but I don't have any

Where can I switch on the remote unlock feature?
Or what needs to be done to get it running?

Regards

Gerhard

### Relevant log output

```shell
none
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
I don't know how it works with google home, but for example Alexa does not allow remote unlocking by default. For good reasons. You have to select the device in Alexa, go to its settings (still in alexa) and activate remote unlocking.

**Comment by gklank** [comment]
Hi,

one point more in detail...

The unlock is functioning by pressing the open button in the Google home app.

But not via voice, then telling that unlock is not possible from remote...

But locking the smart lock via voice is functioning.

Regards 

Gerhard

**Comment by t0bst4r** [comment]
Yes, as mentioned: It's security feature of GH / Alexa etc.
They allow locking by voice, but not unlocking. 

You can workaround that by using a virtual/template switch in HA which locks and unlocks your door.
Or in Alexa you could create a routine which unlocks it. Or you can try to find the settings in GH where you can enable voice unlocking.

But anyway this is not an issue with HAMH. Therefore closing this issue.

**Comment by gklank** [comment]
Of course you are right, I should rise the question in the GH arena.

thx anyway!!!
