### ISSUE TITLE
[Bug]: Homematic Switch is not working

### ISSUE THREAD

**Issue by Marty56** [t0bst4r/home-assistant-matter-hub#304]
### Version

3.0.0-alpha.54

### Matter Controller

Alexa

### Steps to reproduce

I am trying to add an Homematic Switch by using a label.
The Switch is not appearing in the hub even after restarting the Addon.

### State and attributes

N.A.

### Relevant log output

```shell
N.A.
```

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
How did you name your label?

> - Labels in Home Assistant are technically represented by their "slugs".
> - Slugs are technical identifiers used in the background.
> - Slugs are always lowercase and only allow a-z and underscores, so everything else will be replaced with an underscore.
> - Even when renaming a label, the slug doesn't change. Never.
>
> All available/existing labels can be checked using the {{ labels() }} or {{ labels("light.my_entity") }} template in Home Assistant.

**Comment by Marty56** [comment]
Ok. I do not think that the problem is related to labels.
Maybe it is because the homematic switch is a wall plug that can switch two circuits.

**Comment by t0bst4r** [comment]
Is it a "switch" entity in home assistant? If yes, it should work.
Did you add the label to the "device" or to the "entity" in Home Assistant?

**Comment by Marty56** [comment]
I have added the label to the device.

**Comment by t0bst4r** [comment]
I assume that it’s not working after you add the label to the entity, correct?

**Comment by Marty56** [comment]
1. I first added the label to the device. This was not working.
2. Then I added the label to the entity. It is showing up in devices in the add-on but is not recognized in the Alexa App. So it is also not working.
3. I removed the label from the device. Like 2.

Between every step I have also restarted the add-on.

**Comment by t0bst4r** [comment]
If it's showing in the UI then it is working. You have to ask Alexa to search for devices again.
