### ISSUE TITLE
0 Devices - Label "matterhub"

### ISSUE THREAD

**Issue by Suschibomber** [t0bst4r/home-assistant-matter-hub#305]
### Device type

Every labeled device

### Matter Device

rollershutter

### State and attributes

No Device

### Documentation & Issues

- [X] I have reviewed the list of [currently supported entities and their limitations](https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#5-supported-domains--device-types).
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar requests.
- [X] I have [checked](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md) if my controller is known to support the requested device type.

**Comment by t0bst4r** [comment]
How did you name your label?

> - Labels in Home Assistant are technically represented by their "slugs".
> - Slugs are technical identifiers used in the background.
> - Slugs are always lowercase and only allow a-z and underscores, so everything else will be replaced with an underscore.
> - Even when renaming a label, the slug doesn't change. Never.
>
> All available/existing labels can be checked using the {{ labels() }} or {{ labels("light.my_entity") }} template in Home Assistant.

**Comment by w-hayek** [comment]
Hi, I have the same issue. I put several devices but my matter bridge can't find any devices.
My laber is named: matteritems

Many thanks
Wassim

**Comment by Suschibomber** [comment]
@t0bst4r

I called the label matterhub and assigned this label to 3 devices. One roller shutter, one temperature sensor and a smart socket. 

I have deliberately paid attention to lower case. 

So I have already completely restarted the host HA, cleared the cache and restarted the addon and tried "rebuild".

**Comment by Suschibomber** [comment]
> Hi, you should label your entity and not your device.
> This was my failure at the beginnig :-)
> 
> Regards
> Wassim

That was the mistake. Thank you very much. @t0bst4r That was the mistake. Thank you very much. @ that should perhaps be explicitly mentioned in the documentation, so that others are not as stupid as I am 🙈😂
