### ISSUE TITLE
[Connection Issue]: Alexa is working, GH not

### ISSUE THREAD

**Issue by KoLSMS** [t0bst4r/home-assistant-matter-hub#310]
### Version

3.0.0-alpha.55

### Matter Controller

Google Home

### Things you tried

Hello,

the addon works great with Amazon Alexa, but after Binding a new Bridge to GH all devices are marked as offline...

May be it is a Bug or is the mistake on my Site?!

Thanks for your Work on this great addon!!!

### Relevant log output

```shell
.
```

### What deployment method do you use?

Home Assistant AddOn

### Did you already check the following?

- [ ] Does your network include any VLAN setup?
- [ ] Do you have any special firewall rules / services in place?
- [x] Is IPv6 enabled in your LOCAL network?
- [ ] If you are using the docker deployment: Is IPv6 enabled within your docker daemon config?
- [ ] If you are using the docker deployment: Do you run the container with host network?

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
You didn’t checked the IPv6 checkbox. Does it mean that ipv6 is deactivated in your local network?
This is required for GH to see services as online and to control them

**Comment by KoLSMS** [comment]
> You didn’t checked the IPv6 checkbox. Does it mean that ipv6 is deactivated in your local network? This is required for GH to see services as online and to control them

Hello,

Ipv6 is enabled in the local Network...

Thx for further help

**Comment by t0bst4r** [comment]
Can you describe your setup a bit?
How are you running HA? Physical Server (e.g. raspberry) or virtual machine (e.g. proxmox)?
Do you have any special network setup in place? VLANs / Subnets? Is GH in the SAME VLAN/subnet?
Are you REALLY sure that IPv6 is enabled. Please verify with ping6 from another machine in the same subnet/vlan.

Do you have any related addons running on the same HA instance? E.g. the official matter addon, or the old matterbridge addon?

**Comment by KoLSMS** [comment]
> special network setup

Hello,

i am running HA on a virtual machine with proxmox, ip 6 is in my router enabled and working fine, i checked this several times

i use the official matter addon from HA, no special addons or the old matterbridge...

Alexa is working very fine, only at GH all devices are marked as offline :/

**Comment by KoLSMS** [comment]
[491eb00d_hamh_2024-12-18T15-05-47.733Z.log](https://github.com/user-attachments/files/18184465/491eb00d_hamh_2024-12-18T15-05-47.733Z.log)

maybe it helps to find the problem?

i deleted the binding to GH and did the setup again... this is the log after adding the bridge to GH

**Comment by KoLSMS** [comment]
hello, i am very stupid i think...

i had no google hardware at my home network for example an google home mini...

after buying a google home mini i set it up in my local network and then directly google home worked, all devices are online over the matterhub...

sorry for opening the issue...

thx

**Comment by KamilKeenan** [comment]
so additional G-Home hardware is needed? I connected Apple Home without any additional devices (other than HA server with Zigbee Dongle).

**Comment by KoLSMS** [comment]
> so additional G-Home hardware is needed? I connected Apple Home without any additional devices (other than HA server with Zigbee Dongle).

After adding a Google Home Mini to my local Network the Matter hub worked and all devices were online in Google Home...
