### ISSUE TITLE
[Bug]: Cover voice control from alexa

### ISSUE THREAD

**Issue by moz4r** [t0bst4r/home-assistant-matter-hub#311]
### Version

3.0.0-alpha.55

### Matter Controller

Alexa

### Steps to reproduce

Affect a new voice command / routine to the published cover device. 

Thank you for the great work ! Anyone tried to voice command a cover ? Alexa app say it is unsupported. I used it previously with tuya it was ok.  Maybe it is because the virtual state of the cover ( I dont need it )

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by Apollon77** [comment]
Please request support for the specific devicetype on Amazon side because if the assistant do not understand you they need to implement it too ... And yes no t all device types are supported by all controllers

**Comment by moz4r** [comment]
thanks for your answer! I succeeded by using a little trick, I created a virtual switch in HA and with the automations linked to the actions in the store. Now the voice commands work with the virtual switch in alexa ! greetings
