### ISSUE TITLE
[Device]: Can't use Labels

### ISSUE THREAD

**Issue by TRiiPlxXx** [t0bst4r/home-assistant-matter-hub#312]
### Device type

Light and Switch

### Matter Device

.

### State and attributes

Hello, I wanted to add a label to my devices like in the video by Simon42. I named the label exactly the same, wrote it in lower case for “include” and restarted Home Assistant or the add-on several times, but the entities are not displayed.

However, if I use a pattern such as light.*, all the corresponding devices are added.

I think the project is great, but unfortunately it doesn't quite work for me yet :)

### Additional remarks

I habe the latest version. I used Entities ;)

### Documentation & Issues

- [X] I have reviewed the list of [currently supported entities and their limitations](https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#5-supported-domains--device-types).
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar requests.
- [X] I have [checked](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md) if my controller is known to support the requested device type.

**Comment by TRiiPlxXx** [comment]
![2024-12-16 00_03_37-Entwicklerwerkzeuge – Home Assistant](https://github.com/user-attachments/assets/d431fb91-62a3-4430-9896-16042f6f7e9f)
![2024-12-16 00_03_57-Einstellungen – Home Assistant](https://github.com/user-attachments/assets/ed3af096-719e-4c4b-a345-4e446ece72c6)

**Comment by AJErazzor** [comment]
I can confirm the same issue for me - using HAOS addon.

**Comment by TheImproof** [comment]
I can also confirm this behaviour. I have multiple cover entities that I had to add using a pattern, because the label didn't work. However I have 2 cover groups where the label DID work.

**Comment by t0bst4r** [comment]
- Make sure to add the labels on the entity and not on the device.
- Please validate your labels as in the screenshot above using the `{{ labels() }}` template.
- When entities are changed (e.g. add or remove labels) we won't get notified, so you need to trigger a change on the bridge (simply edit the bridge and save without changes). Or you could simply restart the addon.

**Comment by TRiiPlxXx** [comment]
1. I only used Entities 
2. The screenshots above is already the function.
3. I restarted multiple times but it didn't work.

**Comment by mgraebi** [comment]
@TRiiPlxXx 
Your screenshot shows a label named "thread_gerate". Please delete the label "MatterHub" and create it again. Then validate your labels using the {{ labels() }} template again.

Simon42 explained it a little bit wrong in the video. **Only entities** can be labeled for HAMH.

**Comment by TRiiPlxXx** [comment]
Deleting the old label and using a new one worked for me!

Thanks!

**Comment by TRiiPlxXx** [comment]
Deleting the old label and using a new one worked for me!

Thanks!
