### ISSUE TITLE
[Network] No Fabric and Devices Offline

### ISSUE THREAD

**Issue by kramttocs** [t0bst4r/home-assistant-matter-hub#32]
This may very well be something on my network side but looking for some direction.

QR Code shows Commissioned banner but Fabrics shows ?
Added to a new Google Home via a Nest Audio.

Not seeing anything that stands out in the Add On logs.

Worth noting the same happened with your previous add on so again, I fully expect this to be on my end.

**Comment by leonardpitzu** [comment]
Same for me... no errors in logs or anything. Network is from unify, hub is a LG smart tv. Pairing done through LG Thinq.

**Comment by t0bst4r** [comment]
@kramttocs 
Do you also have a unify network? I have seen larger discussions in the old repo about that. I’ll look them up and try to extract a solution 😂

**Comment by kramttocs** [comment]
Hey  @t0bst4r  - no, I have an Asus setup with several AIMesh nodes.
I did a lot of reading yesteday and messing with router configs but no luck. 
I came across the unifi stuff though so that might help @leonardpitzu 

Some links:
https://community.home-assistant.io/t/configuration-unifi-for-matter/671315
https://github.com/t0bst4r/matterbridge-home-assistant/issues/176
https://github.com/Luligu/matterbridge/issues/92

**Comment by kramttocs** [comment]
I just deleted my home and started over.  I did notice that Google Home would automatically find the matter device but never connect. I then switched my phone wireless to my 2.4ghz and it did the whole generate/adding very quickly.
My nest speaker is on my 5ghz though yesterday I purposely connected it to 2.4 when I created a new home then.

The Fabrics in the bridge still shows a ? though hovering over it gives me an adminVendorID value. Any idea why it's '?'  ?

**Comment by kramttocs** [comment]
Also...

The fact that it can find it  automatically is interesting.
I know nothing about Matter beyond what I googled yesterday (mDNS and such) but the fact that it can find it automatically makes me think that all that (meaning my router) is ok. 

Since the HA Matter Hub is acting like a central point and hardwired to the router, I wouldn't think there will be the complications there could be if there were a 100 different actual Matter devices connected to wifi themselves.

Don't really have any good questions beyond 'why does it not work?' :) but just wondering if there are some key things to how this Matter Hub is presenting itself that might give some clues I can follow.

**Comment by leonardpitzu** [comment]
In my case the TV and HA are both wired, connected to a Unifi Cloud Gateway Max. I can do the pairing and all goes well until the last step (at least this is how it’s depicted in the LG Thinq app). The last step called “connection” fails and errors out with a “decide already connected” message. The bridge appears as commissioned. No devices are visible in the Lg Thinq app.

**Comment by kramttocs** [comment]
Oh, that's a different issue than mine

**Comment by heatiell** [comment]
Hello,
I didn't know if it's the issue you encountered but just to let you know in case you don't, Matter with Google Home require to have ipv6 configured. I had the same issue with the previous addons and once ipv6 was configured, it worked. I don't know about LG thinq but it could be something similar

**Comment by leonardpitzu** [comment]
I already have IPv6 and it works ok. mDNS as well.

**Comment by kramttocs** [comment]
Mine should also be working as the HA console shows an IPv6 address and the fact that Google home can find the matter hub and add the devices (just all offline) but is there another way to validate?

That's what would be helpful - to know what GH is looking for and a way to test that this hub is providing it or the network is allowing it.

**Comment by heatiell** [comment]
@kramttocs Are you sure that the ipv6 you see is one coming from your router ?
Because HA show also the ipv6 from the internal network of your server. 
Google home can connect to the matter hub without ipv6. But it's after that the issue come. I experienced the exact same behavior as you. And others also with other matter hub like matterbridge for example. So  I suggest you to validate your ipv6 config directly on your router if you can.
If all is good with ipv6, I don't have any other clue on what can happen

**Comment by heatiell** [comment]
@kramttocs Well, after some learning. I realize I was wrong about my own configuration. Just to be sure, to you have VLAN setup ?

**Comment by kramttocs** [comment]
@heatiell No, my setup is pretty simple. Separate 2.4/5ghz and then the AiMesh nodes are the only things unique (if you can call them that) that I can think of. Appreciate the help.

**Comment by heatiell** [comment]
So I tried to reproduce your issue but I didn't success even with changing some parameters on my router. But I miss something I think as should be able to break my own Matter hub but I didn't succeed, and I am missing clues at this stage about what config should work on not. Finally, I'm not so sure your issue is related to IPV6 as your device are on a same LAN/Subnet, so IPV6 should just work

**Comment by kramttocs** [comment]
Again, I appreciate you doing that. That about sums up what I keep finding also: it should just work :)

**Comment by kramttocs** [comment]
Well, I don't understand it but it started working. 
The only changes I had made recently were these: https://www.asus.com/support/faq/1042475/
Then on the IPv6 page of the router I had set it to Tunnel 6to4 and saved with the defaults. 
I have since undone all of those changes and it's still working.
Don't know that it will continue but it's something.

The web ui for the matter hub still shows ? for the Fabric though fwiw

**Comment by t0bst4r** [comment]
ok. that is very strange.
the question mark is my fault. i only configured icons for google, apple and alexa by simply checking if the fabric label includes their brand names.

what **exactly** does it say when hovering the question mark? and what brand / icon should it have?

**Comment by kramttocs** [comment]
![{D783B406-B6EF-49C7-98C1-F2868504CAC2}](https://github.com/user-attachments/assets/7d1e87e6-bb20-4a76-b666-a3eb1a15479a)

This is using Google Home on my Android with a Nest Audio as the device (I will add more speakers/displays later but just testing this one right now).

**Comment by t0bst4r** [comment]
In the meantime i added a mapping to fix that vendor id to be mapped to google. Can this issue be closed then?

**Comment by kramttocs** [comment]
@t0bst4r Yes, thanks for adding that. It can be closed.
Thanks @heatiell for looking at this also.
