### ISSUE TITLE
[Bug]: call_service event is not sent to HA Event Bus if the state doesnt change 

### ISSUE THREAD

**Issue by Kaskadeur111** [t0bst4r/home-assistant-matter-hub#320]
### Version

3.0.55

### Matter Controller

Alexa

### Steps to reproduce

Create a helper switch entity
in Developer tools monitor "call_service" events.
Send "Alexa, turn off switch"

If the switch is ON before, a call_service event is fired and logged, if the switch is OFF no call_service event is logged...

In matterbridge 2.9 this worked.

Causes Problems with every kind of switch that needs to receive ON and OFF commands to trigger automations.

### State and attributes

event_type: call_service
data:
domain: input_boolean
service: turn_off
service_data:
entity_id:
- input_boolean.zahn
origin: LOCAL
time_fired: "2024-12-16T18:07:02.553251+00:00"
context:
id: 01JF8ADWWR96HRG91D74H3M68E
parent_id: null
user_id: 42e1fd0bd3084a22873a1bfc0c659ee3

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
But… why should we turn it on if it’s already on?
Is that really the problem or shouldn’t you design your automation trigger differently?

**Comment by Kaskadeur111** [comment]
OK, ich versuchs mal in deutsch :-)

bin gestern auf die Matterbridge zurück, weil meine ganzen Leuchtengruppen nicht mehr zuverlässig funktionierten.
An einem ganz einfachen Beispiel:

Du hast einen Helfer:  "Weihnachtsbeleuchtung" als Leuchtengruppe angelegt mit 2 Geräten darunter "Schwibbogen" und "Weihnachtsbaum".

Mit Alexa sage ich "Weihnachtsbeleuhtung an" -> Beide Geräte gehen an... (Helfer ist true und beide geräte auch.

Jetzt schaltet irgendjemand den Schwibbbogen aus -> helfer ist immer noch true, aber nur eins der beiden Geräte ist wirklich an.

Wenn ich jetzt wieder sage "Weihnachtbeleichtung an" -> passiert mit dem Matterhub nichts mehr und mit der Matterbridge wird die Gruppe korrekt wieder komplett angeschaltet.

Dafür gibt es glaube ich keinen "Workarround". Selbst wenn man die Gruppe "Weihnachtsbeleuchtung" so einstellt, dass sie auf "false" geht sobald eines der Geräte ausgeschaltet wird, hat man das gleiche Problem in die andere Richtung... man kann sie zwar einschalten, aber nicht aus.

Das Problem, habe ich mit allen Leuchtengruppen (Ich habe eine Gruppe Küchenlicht, eine Gruppe Arbeitsplatten, eine Gruppe Heizung.

Quasi alles was mehrere Geräte die getrennt geschaltet werden können als einheit wieder ein oder ausgeschaltet werden soll funktioniert nicht.

:-)

**Comment by t0bst4r** [comment]
Okay, guter Punkt. Für die on/off commands würde ich das noch akzeptieren. Bei Attributen wie brightness oder anderen devices, wie climates, wäre ich allerdings vorsichtig, da hier das Risiko von unendlichen Updates entstehen kann, wenn z.B. durch Rundung ständig die Updates zwischen matter und ha hin und her gesendet werden.

**Comment by thezeus123** [comment]
@Kaskadeur111:
Dazu in der helper Gruppe "alle Entinitäten" aktivieren. 
Damit wird die Gruppe nur "on" wenn alle entinitäten auch "on" sind
![image](https://github.com/user-attachments/assets/5d5ae2a0-7ac9-44ee-bde4-c0a0a5fd36ee)

**Comment by kennylevinsen** [comment]
If your matter controller supports grouping lights (Apple Home does for example, while Google Home requires you to put them in a distinct "room"), it might work better to expose the lights individually and group things there. That way your controller knows what's going on and what you are trying to do.
