### ISSUE TITLE
[Feature]: Rolladensteuerung

### ISSUE THREAD

**Issue by huwayyy** [t0bst4r/home-assistant-matter-hub#325]
### Requested feature

Servus, erstmal vielen Dank für das super Addon!

Ich habe jetzt meine Rolläden über dein Addon in Alexa eingebunden (Vorher über NodeRED Alexa local) 
Wenn ich bei der alten integration gesagt habe: Alexa Rolladen hoch/runter, dann ist der Rolladen auf/zu gegangen.

Jetzt mit deinem addon fährt der Rolladen um 1% hoch oder runter. 1% Schritte machen meines Erachtens keinen Sinn bei einem Rolladen. Entweder wäre hier auf/zu gut, oder halt in größeren Schritten. (Müssten uns dann zwar nach jahrelanger Nutzung neue Kommandos aneignen ;-) ) 

### Documentation & Issues

- [X] I have reviewed the list of [currently supported entities and their limitations](https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#5-supported-domains--device-types).
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar requests.
- [X] I have [checked](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md) if my controller is known to support the requested device type.

**Comment by doubleusee39** [comment]
Mach dir einfach eine Routine in Alexa mit dem Namen Rolladennamen hoch und eine für runter und stell in der jeweiligen Lage 0 oder 100% ein. Funktioniert bei mir perfekt.

**Comment by huwayyy** [comment]
> Mach dir einfach eine Routine in Alexa mit dem Namen Rolladennamen hoch und eine für runter und stell in der jeweiligen Lage 0 oder 100% ein. Funktioniert bei mir perfekt.

Ich lege mir doch nicht noch extra für alle Rolläden je 2 Routinen an 🙈 das hat ja vorher auch ohne Routine funktioniert. Es macht null sin ein Rollo in 1% Schritten hoch und runter zu fahren über Sprachbefehle.



> @huwayyy du kannst hier einfach "Rolloname öffnen" bzw. "Rolloname schließen" sagen und er fährt dann in die jeweilige Endlage.

Danke, muss man jetzt nur nen bissl umdenken. Wenn man Jahre lang hoch/runter gesagt hat 😁 für mich nicht das Problem, aber erklär das Mal der Frau.

**Comment by ohrenmasken** [comment]
Dann eben von nun an auf und zu oder öffnen und schließen. Das mit der 1 % Steuerung macht bei Jalousien total Sinn, weil man damit den Neigungswinkel der Lamellen einstellen kann.

**Comment by t0bst4r** [comment]
Auf die Sprachkommandos von Alexa habe ich leider keinen Einfluss. Alexa sendet bei "hoch" leider einen "bewege um 1% nach oben" Befehl.
Ich führe nur aus, was Alexa an mich weiter gibt.
