### ISSUE TITLE
[Feature]: Trigger automations

### ISSUE THREAD

**Issue by dennisvandehoef** [t0bst4r/home-assistant-matter-hub#326]
### Requested feature

Currently, an automation is exported as a switch.
This means that from ALexa, I can only enable/disable the automation but I whould like to trigger/run it.

If this is not possible, we probably want to improve this in the readme 😸 

### Documentation & Issues

- [X] I have reviewed the list of [currently supported entities and their limitations](https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#5-supported-domains--device-types).
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar requests.
- [X] I have [checked](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md) if my controller is known to support the requested device type.

**Comment by adegenkolbe** [comment]
Same would be cool for scripts too

**Comment by knuti1960** [comment]
I tried this with a HA-script in Home (Google), it works. I say: "Hey Google, lock PC", and the script is executed immediately, the PC is locked. Should also work with Alexa.

**Comment by t0bst4r** [comment]
For scripts and automations I am sending the generic `homeassistant.turn_on` and `turn_off` commands.

If that doesn't work we can easily change that. 
Can you please verify that using the HA dev tools?

**Comment by nick-fisch** [comment]
> I tried this with a HA-script in Home (Google), it works. I say: "Hey Google, lock PC", and the script is executed immediately, the PC is locked. Should also work with Alexa.

I can confirm this. Starting an automation using Google Assistant does not do anything. Starting a script from Google Home that just runs the automation works.

**Comment by knuti1960** [comment]
Now I tried it with 2 different automations, one for vac room cleaning, one for turning off a lightgroup, both don't work with google home. 
Unfortunately, I am not familiar with the HA developer tools.

**Comment by thor9898** [comment]
I think this gave me a problem, as I was passing through my automation to Google Home to be able to enable it or disable it, but now it just triggers it. Is there any way to enable or disable it without having to create a helper or another automation?

**Comment by thor9898** [comment]
> Is there any way to enable or disable it without having to create a helper or another automation?

Is there any plan to give this as an option in the bridge's settings?
