### ISSUE TITLE
[Bug]: HA Addons Error2024.12.4: https://github.com/t0bst4r/home-assistant-matter-hub.git is not a valid add-on repository

### ISSUE THREAD

**Issue by korniza** [t0bst4r/home-assistant-matter-hub#335]
### Version

2024.12.4

### Matter Controller

N/A

### Steps to reproduce

 try to add the repository on HA Addons. The error message is  https://github.com/t0bst4r/home-assistant-matter-hub.git is not a valid add-on repository.

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
> https://github.com/t0bst4r/home-assistant-matter-hub.git

Is that the url you used? You need to add it without the `.git` part.

**Comment by korniza** [comment]
Thank you! 
My mistake! false alarm :)

**Comment by eliasto** [comment]
Hi, I have the same error but I tried by putting `https://github.com/t0bst4r/home-assistant-matter-hub`.
<img width="649" alt="Screenshot 2024-12-30 at 00 07 54" src="https://github.com/user-attachments/assets/1df56e26-7bb8-438a-9958-0203ec9b7717" />
