### ISSUE TITLE
[Bug]: Docker container not able to connect to HA

### ISSUE THREAD

**Issue by NopeOo** [t0bst4r/home-assistant-matter-hub#347]
### Version

release v3.0.0-alpha.57

### Matter Controller

Alexa

### Steps to reproduce

Just start the container with the address of the HA instance + token.

It says it can not connect to HA instance ( 192.168.178.4:80 ) until i add a 'sleep 30 &&' at the beginning of the start command which results in "/bin/sh -c 'sleep 30 && home-assistant-matter-hub start' "

### Documentation & Issues

- [X] I have reviewed the [documentation](https://github.com/t0bst4r/home-assistant-matter-hub/blob/main/packages/documentation/README.md) and the linked troubleshooting guide.
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar problem.

**Comment by t0bst4r** [comment]
Does it happen on every start of the container, or only when HA is restarting, too?
Can you please post the exact error message?

**Comment by NopeOo** [comment]
Hey Tobias,

Thank you for taking a look at it.

Here is the Docker log output:

`[ 2024-12-29T21:12:55.385Z ] [ INFO  ] [ WebApi                                             ]: HTTP server (API & Web App) listening on port 80
[ 2024-12-29T21:12:58.435Z ] [ ERROR ] [ Matter / Logger                                    ]: Unhandled error detected: Unable to connect to home assistant with url: http://192.168.178.4:80/
  at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:783:14)
  at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:775:18
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:769:23)
file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:783
      return new Error(
             ^

Error: Unable to connect to home assistant with url: http://192.168.178.4:80/
    at _HomeAssistantClient.parseError (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:783:14)
    at file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:775:18
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _HomeAssistantClient.initialize (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:769:23)

Node.js v20.18.1`

If there is another useful internal log, pls let me know.

I'm running the container on a qnap nas with network at bridge mode and a static ip.

The image is 3.0.0-alpha.57

Best regards,
Patrick
