### ISSUE TITLE
[Feature]: Cover Tilt Support

### ISSUE THREAD

**Issue by florianfiby** [t0bst4r/home-assistant-matter-hub#349]
### Requested feature

This add-on is working perfectly in my KNX based house with Home Assistant and google nest audio
My covers also support tilt. As far as I can see, matter js also supports tilt.

As an workaround, I'm using HA Scene for setting tilt on my covers.

### Documentation & Issues

- [X] I have reviewed the list of [currently supported entities and their limitations](https://github.com/t0bst4r/home-assistant-matter-hub?tab=readme-ov-file#5-supported-domains--device-types).
- [X] I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar requests.
- [X] I have [checked](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md) if my controller is known to support the requested device type.

**Comment by mt0321** [comment]
Sharing this example of the [iBlinds v3](https://myiblinds.com/products/iblinds-kit-v3-2) Z-Wave device, which _only_ supports tilt (not open/close), in case it helps.

**cover.main_bedroom_blinds:**
```
current_tilt_position: 0
device_class: blind
supported_features: 240
```

240 is open_tilt + close_tilt + stop_tilt + set_tilt_position:
```
SUPPORT_OPEN = 1
SUPPORT_CLOSE = 2
SUPPORT_SET_POSITION = 4
SUPPORT_STOP = 8
SUPPORT_OPEN_TILT = 16
SUPPORT_CLOSE_TILT = 32
SUPPORT_STOP_TILT = 64
SUPPORT_SET_TILT_POSITION = 128
```
