### ISSUE TITLE
[Bug] Filter->include->labels not showing devices

### ISSUE THREAD

**Issue by MitoKafander** [t0bst4r/home-assistant-matter-hub#35]
Bridge doesn't find devices that have the corresponding labels attached to them. Example below. I have tried adding a "for_google_home" label to some devices and configured the bridge like below and it doesn't find the devices. If I change the type to "domain" and value to "light", i do get devices.

```
{
  "name": "",
  "port": 5540,
  "filter": {
    "include": [
{
        "type": "label",
        "value": "for_google_home"
      }
],
    "exclude": []
  }
}
```

**Comment by DJBenson** [comment]
I use this and it works fine;

```
{
  "name": "Main",
  "port": 5540,
  "filter": {
    "include": [
      { "type": "label", "value": "matter" }
    ],
    "exclude": []
  }
}
```

**Comment by DJBenson** [comment]
I created a bridge with your config (just amended the port) and it worked.

<img width="1403" alt="image" src="https://github.com/user-attachments/assets/1bfc8947-532f-4d8f-ad5d-0b236fc98829">

**Comment by jesusgcas** [comment]
I did the same and for me it’s not working. I copied your code, created and assigned the label with no luck.

**Comment by t0bst4r** [comment]
Could you please verify if the label is correct.

go to developer settings in home assistant, then open the "template" tab. 

Paste the following, replace the entity id. 

```
{{ labels("light.my_entity") }}
```

to see a list of all available labels:

{{ labels() }}

**Comment by jesusgcas** [comment]
> Could you please verify if the label is correct.
> 
> go to developer settings in home assistant, then open the "template" tab.
> 
> Paste the following, replace the entity id.
> 
> ```
> {{ labels("light.my_entity") }}
> ```
> 
> to see a list of all available labels:
> 
> {{ labels() }}



Thanks for you answer.

Here you can see all the labels, the last one is the one I'm using.
![image](https://github.com/user-attachments/assets/4bd4867c-4382-4bb2-a324-2b0a24cfdb0d)

This is one entity on templates tab
![image](https://github.com/user-attachments/assets/0ba116a6-96e6-4887-aead-892a4790eec3)

The label is applied to the entity
![image](https://github.com/user-attachments/assets/8a0a937e-8489-4a47-a7d9-4cfa62bbaf30)

The code to create the hub:
![image](https://github.com/user-attachments/assets/e9762368-b389-40cc-887a-6f26d2a69b63)

And the result:
![image](https://github.com/user-attachments/assets/e419619d-f1b6-4be7-ae19-696a61f4d464)

**Comment by MitoKafander** [comment]
> > Could you please verify if the label is correct.
> > go to developer settings in home assistant, then open the "template" tab.
> > Paste the following, replace the entity id.
> > ```
> > {{ labels("light.my_entity") }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to see a list of all available labels:
> > {{ labels() }}
> 
> Thanks for you answer.
> 
> Here you can see all the labels, the last one is the one I'm using. ![image](https://private-user-images.githubusercontent.com/177886707/381601781-4bd4867c-4382-4bb2-a324-2b0a24cfdb0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDE5MTcsIm5iZiI6MTczMDMwMTYxNywicGF0aCI6Ii8xNzc4ODY3MDcvMzgxNjAxNzgxLTRiZDQ4NjdjLTQzODItNGJiMi1hMzI0LTJiMGEyNGNmZGIwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNTIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWQzNzY1MWFlNGI2YzdjNDAwYzg2ZjlkNmFiYjFmMmMzYTI0OTZkODkwZTc4NzhlZmRmYTU3OGI5ZjM4YTZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cWG1dUr6j_jFn3f-b2vIQMCnVLtcCYkMfJagLAioAKw)
> 
> This is one entity on templates tab. I understand here all labels should appear but they don't. ![image](https://private-user-images.githubusercontent.com/177886707/381600505-0ba116a6-96e6-4887-aead-892a4790eec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDE5MTcsIm5iZiI6MTczMDMwMTYxNywicGF0aCI6Ii8xNzc4ODY3MDcvMzgxNjAwNTA1LTBiYTExNmE2LTk2ZTYtNDg4Ny1hZWFkLTg5MmE0NzkwZWVjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNTIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjViY2Q5NzQxZTUzYTNkNmMwZWEyNTYxNDE5MzNjYjdkMDgxZTk1YjBkMDVjMmUzYmU5OGNmMmQ2YTEyMTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._FVwCGeQaFEVHT6kmmdM5c0_3mCs4eXNgY_3CZ1GqAM)
> 
> The label is applied to the entity ![image](https://private-user-images.githubusercontent.com/177886707/381602333-8a0a937e-8489-4a47-a7d9-4cfa62bbaf30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDE5MTcsIm5iZiI6MTczMDMwMTYxNywicGF0aCI6Ii8xNzc4ODY3MDcvMzgxNjAyMzMzLThhMGE5MzdlLTg0ODktNGE0Ny1hN2Q5LTRjZmE2MmJiYWYzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNTIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjFmNzFmZWIyNGY1ZGZhYTc2MDMzMjk2MjA3ZDExYjAxNTJiNjliN2VhYzYwNzJkOGFhMjZlYjQ4YmIwOGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WiUum9MFaIS9tnSVYQdxknVx9Orp9udAyilaJlWrVQs)
> 
> The code to create the hub: ![image](https://private-user-images.githubusercontent.com/177886707/381603639-e9762368-b389-40cc-887a-6f26d2a69b63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDE5MTcsIm5iZiI6MTczMDMwMTYxNywicGF0aCI6Ii8xNzc4ODY3MDcvMzgxNjAzNjM5LWU5NzYyMzY4LWIzODktNDBjYy04ODdhLTZmMjZkMmE2OWI2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNTIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNWEyOWI3NWY4NzI5ZGQ4MGZlZTI2OTFjYzhhODJhNTQwYjk4OTliNmFlNWQ5NWUyZGQ5MzEzYmQyYTFlOGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.xRY0WmrWt1Ptvt0ZGP8IaB2vVXr_pY4ruTfJiHJbd4U)
> 
> And the result: ![image](https://private-user-images.githubusercontent.com/177886707/381603981-e419619d-f1b6-4be7-ae19-696a61f4d464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzMDE5MTcsIm5iZiI6MTczMDMwMTYxNywicGF0aCI6Ii8xNzc4ODY3MDcvMzgxNjAzOTgxLWU0MTk2MTlkLWYxYjYtNGJlNy1hZTE5LTY5NmE2MWY0ZDQ2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxNTIwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjIwNzBiMWM0MzQ2MzkxMDIyZGFjMjEwMTUwZmVmMWZlZDNhY2FhZjMyZTcwNzhmODE0MzY5Yjg4ZmEyYTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s3vUeCo-jLFu9dhD5sWqzAxcE1QZ5t01R3olhlLl2ps)

Ok. I do see a list of labels but it seems like they are some previous ones i used at some point and not the ones i have currently assigned the light.

Currently i have "matter" as the label but in the template it shows three other ones and no "matter".

So I tried the bridge with a label that shows in the template editor but the bridge still doesn't find it.

**Comment by MitoKafander** [comment]
Just to clarify. The bridge works when I label devices or entities?

**Comment by MitoKafander** [comment]
OK. did a fresh install of HA and restored a backup. Now the labels are showing correctly:

{{ labels("light.office_light_1") }}

[
  "lights",
  "office_lights",
  "matter"
]

Input to the bridge:
{
  "name": "Main",
  "port": 5540,
  "filter": {
    "include": [
      { "type": "label", "value": "matter" }
    ],
    "exclude": []
  }
}

![image](https://github.com/user-attachments/assets/1d43d1ac-f911-429d-8a03-5b0d30231032)

**Comment by hcuamatzi** [comment]
Hello, I am in the same situation, initially I thought I was doing something wrong, but apparently settings are correct and it's not working :(
![image](https://github.com/user-attachments/assets/a0060f1b-7b2b-4cef-8e8d-9a058c79a650)
![image](https://github.com/user-attachments/assets/3f4570c7-1280-4bc5-ac70-f4fc0be07e15)
![image](https://github.com/user-attachments/assets/6682ec37-e135-4b78-9bdf-25ff35933fb4)

Not sure if there is anything I can do to help testing this out

**Comment by hcuamatzi** [comment]
Right!, I completely forgot to update before posting, after the hub loaded with the update it refreshed the list and all were listed this time.

Adding to that, I added more devices, and they were not updated in the bridge, also deleted another label I was testing with, and the devices remained in the bridge list.

I restarted the add-on and that worked to update the devices in each bridge with the corresponding labels.

Not sure if this is the expected behavior but for now that seems to be what works for me.

**Comment by MitoKafander** [comment]
OK got it working somehow resetting my whole setup in the process. Worth it tho as now the bridge picks up on the labels if they have been assigned before the add-on was installed. Also picks up on newly labelled devices when the add-on is restarted.

Thanks for the help guys!

**Comment by t0bst4r** [comment]
Sorry for the confusion. Due to performance reasons the Home Assistant Entity Registry is only loaded once at startup. After that the app subscribes to the states of all entities which are included in at least one bridge. Labels are stored in the registry so you need to restart the app to refresh labels.
Same is valid when adding new entities to home assistant. The app needs to restart to find those new entities.

**Comment by jonlanceley** [comment]
For me i had to add a brand new label to an entity for it to be picked up. Renaming one doesnt work, HA still used the old name,  used the developer tools example above to check.

So add new label, if using spaces in the matter config replace spaces with underscore. I also made sure in the matter config it only used lowercase chars.

E.g. label in HA is Expose to Matter Bridge

In Matter bridge config:

{
  "filter": {
    "include": [
      {
        "type": "label",
        "value": "expose_to_matter_bridge"
      }
    ],
    "exclude": []
  }
}
