### ISSUE TITLE
[Bug] HA changed states are not reflect in Google Home

### ISSUE THREAD

**Issue by pkoutsovasilis** [t0bst4r/home-assistant-matter-hub#37]
Sorry if I fail to describe this precisely but when I have a script that switches a switch on, the switch is not reflect as on neither in Google Home nor in the UI of the matterhub (I waited multiple times for the countdown to occur) 🙂 

logs:
```
matterhub-1  | [ 2024-10-29T23:48:08.817Z ] [ INFO  ] [ matter.js / Behavior                     ]: Invoke ae76b4970d074c6ab72a324c9bd8b682.aggregator.script_boiler_turn_on_10_minutes.onOff.on online#743ab83@220268e7 (no payload)
matterhub-1  | [ 2024-10-29T23:48:24.837Z ] [ INFO  ] [ matter.js / Behavior                     ]: Invoke ae76b4970d074c6ab72a324c9bd8b682.aggregator.switch_boiler.onOff.on online#743ab86@220268e7 (no payload)
matterhub-1  | [ 2024-10-29T23:48:27.705Z ] [ INFO  ] [ matter.js / Behavior                     ]: Invoke ae76b4970d074c6ab72a324c9bd8b682.aggregator.switch_boiler.onOff.off online#743ab89@220268e7 (no payload)
matterhub-1  | [ 2024-10-29T23:48:46.803Z ] [ INFO  ] [ matter.js / MatterDevice                 ]: All announcements expired
```

**Comment by truongbber** [comment]
i also have the same problem, unresponsive status to google home, and if it is possible to customize the device name and room setting in the configuration it will be good,

**Comment by t0bst4r** [comment]
Your log says that after running your script the switch gets turned on and then immediately off. 
does you switch stay on in HA?

**Comment by pkoutsovasilis** [comment]
> Your log says that after running your script the switch gets turned on and then immediately off. 
> does your switch stay on in HA?

I did click on it from Google Home but instead of turning it off it turns it on because this status is never reflected 😊

**Comment by pkoutsovasilis** [comment]
More on the same issue I face, I have some temperature sensor and neither these are pushing updated values from HA to Google Home 🙂 if I can help somewhat more concretely, except providing high-level observations, please feel free to tell me

**Comment by t0bst4r** [comment]
I’ll need to add some debug logs to detect if the app doesn’t get notified or if it‘s considering it as "no changes".

I’ll add that during the day and then ask you to test it.

**Comment by t0bst4r** [comment]
If you set the log level to debug, you should already see a log line like the following whenever you change the state of an entity:

```
[ 2024-11-01T09:27:00.533Z ] [ DEBUG ] [ matter.js / Transaction                            ]: Transaction setStateOf<d9ef0327a18f48049c43d92568fd4545.aggregator.light_matterextendedlight>#bd locked d9ef0327a18f48049c43d92568fd4545.aggregator.light_matterextendedlight.onOff.state
```

Anyway i have added (alpha.13) another `silly` log, to log everytime home assistant notifies about state changes.
The problem: home assistant always notifies ALL entities when ONE changes.
So I'd recommend deleting all bridges and only create ONE bridge including ONE device. Then you'll only get ONE log message.

**Comment by pkoutsovasilis** [comment]
So to give also some more visual aid below is a screenshot of my boiler switch, I enabled it through HA but the state in matterhub UI remains as off; I waited a couple of minutes before taking the screenshot 

![image](https://github.com/user-attachments/assets/09d4606c-d125-4c0d-941c-c87304cd6a5c)

Here are also the debug logs of the container, I don't see anything related but you definitely know more about these than me 🙂 

[out.log](https://github.com/user-attachments/files/17600000/out.log)

**Comment by t0bst4r** [comment]
Okay, understood. Thank you!
Can you set the log level to "silly"? Then we'll get even more details. I've added a log message for EVERY entity state update coming from HA.

**Comment by pkoutsovasilis** [comment]
Oops `"silly"` me I went only with `"debug"` above 😄 Attached below is the log with "silly" log level

My events from HA:
switch on at 13:35:00
switch off at 13:35:20

[out.log](https://github.com/user-attachments/files/17600098/out.log)

**Comment by t0bst4r** [comment]
So no "silly" logs available, right?
Does it only happen when the switch is turned on/off via script or is NO state at all replicated?
Does it not work for all entities?

That is very strange. Somehow the WebSocket from Home Assistant is not notifying this. I'll try to reproduce this.

**Comment by pkoutsovasilis** [comment]
> So no "silly" logs available, right?
> Does it only happen when the switch is turned on/off via script or is NO state at all replicated?
> Does it not work for all entities?

for the needs of debugging thus I manually pressed the switch on from HA waited a bit to see if the matterhub UI reports this as online and then pressed the switch off just to try and make the logs as extended as possible, so I guess no silly logs

**Comment by t0bst4r** [comment]
okay one more stupid question. did you restart the addon after setting the log level to "silly" ? 😀 
I forgot about that, but the log level is a startup-parameter.

**Comment by pkoutsovasilis** [comment]
yes I had it restarted but here is another attempt with the logs from the start; looking at it I can see that HA sends updates for my climate entities (the first bridge I created) but no updates for any of the entities on the other bridge where the switch resides (second in order bridge I created)

[out2.log](https://github.com/user-attachments/files/17601872/out2.log)

**Comment by pkoutsovasilis** [comment]
after deleting both bridges and creating just a single new one that exposes all devices I can see that the states are reflected properly 🙂 so, I guess this issue is present only with multiple bridges?!

**Comment by t0bst4r** [comment]
Yes, that’s what I assumed from your last message. I’ll have a look.
