### ISSUE TITLE
[Enhancement] Show version number

### ISSUE THREAD

**Issue by ViaudJV** [t0bst4r/home-assistant-matter-hub#38]
Can you show version number somewhere ?

**Comment by joacim69** [comment]
You see it at the top of the addon

**Comment by ViaudJV** [comment]
I use the docker version not the addon.

**Comment by t0bst4r** [comment]
just released a new version:

![grafik](https://github.com/user-attachments/assets/08323a34-6531-4b8d-97ff-b9a45b6d6dd2)

**Comment by ViaudJV** [comment]
cool thx.
