### ISSUE TITLE
[Enhancement] Add fan-only mode to climate

### ISSUE THREAD

**Issue by tammeryousef1006** [t0bst4r/home-assistant-matter-hub#39]
kindly add fan only mode to climate aside of heat and cold modes , 
many thanks

**Comment by pbn42** [comment]
If i can add a little something, i have Gree hvac.
Using your integration, i can set the temperature, but i can't turn it on or off
thanka a lot !

**Comment by tammeryousef1006** [comment]
all function well for me , turn on off , set temp , set mode

**Comment by t0bst4r** [comment]
Can you provide entity state and attributes for fan_only mode?
Open Home Assistant -> Developer Tools -> States and search for your climate entity while it's in fan_only mode.

Thank you!

**Comment by tammeryousef1006** [comment]
hvac_modes:
  - "off"
  - heat
  - cool
  - heat_cool
  - dry
  - fan_only
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes:
  - quiet
  - low
  - medium
  - high
  - turbo
  - auto
current_temperature: 20.1
temperature: 24
fan_mode: high
last_on_operation: fan_only
device_code: 1400
manufacturer: Samsung
supported_models:
  - Unknown
supported_controller: Broadlink
commands_encoding: Base64
icon: hass:air-conditioner
friendly_name: Family Room AC
supported_features: 393

**Comment by tammeryousef1006** [comment]
![Uploading family ac.png…]()

**Comment by tammeryousef1006** [comment]
![family ac](https://github.com/user-attachments/assets/7edd4727-6a85-41b4-98f7-e4d53342c526)

**Comment by tammeryousef1006** [comment]
![Screenshot 2024-11-01 172822](https://github.com/user-attachments/assets/4318cf39-04d2-4d16-9dc4-6b4e5af83e61)

**Comment by pbn42** [comment]
![image](https://github.com/user-attachments/assets/0e2521b4-4701-4247-a740-7ec80058fc35)

**Comment by pkoutsovasilis** [comment]
for the shake of completion here are also mine

One climate entity based on [AirCon integration](https://github.com/deiger/AirCon)

<img width="1029" alt="Screenshot 2024-11-03 at 4 14 30 PM" src="https://github.com/user-attachments/assets/32ee4986-e103-446e-b710-a3d18818e465">

And here is another one based on ESPHome utilising [Midea Air Controller](https://esphome.io/components/climate/midea.html) in Climate platform

<img width="1031" alt="Screenshot 2024-11-03 at 4 14 03 PM" src="https://github.com/user-attachments/assets/00ff0c14-e18f-48a1-800d-e24327d5c5d8">

**Comment by t0bst4r** [comment]
Thank you for your contributions and reports regarding climate/thermostat-related issues. I've noticed that this area has become increasingly complex, with overlapping tickets and discussions. To streamline the process and ensure we address everything effectively, I’ve decided to close the existing tickets on this topic.

Instead, I’m creating a [centralized discussion](https://github.com/t0bst4r/home-assistant-matter-hub/discussions/261) where we can collectively revisit and tackle these challenges in a structured manner. Please feel free to share your insights, reproduce steps, and ideas there.
