### ISSUE TITLE
[Bug] Google Home can't control light Brightness or Colors

### ISSUE THREAD

**Issue by DMedina559** [t0bst4r/home-assistant-matter-hub#4]
Starting a few days ago Google Home with the old [matterbridge-home-assistant](https://github.com/t0bst4r/matterbridge-home-assistant) addon stopped controlling my lights colors, brightness, and white temps. The same issue arises in this new version also so i figured a bug report here would be more fitting than the old repo.

These are the errors I get in the logs with the new addon

```
[ 2024-10-27T18:11:49.092Z ] [ ERROR ] [ matter.js / Transaction                  ]: Rolling back online#faebc02@3b70cf9f due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime
[ 2024-10-27T18:11:49.092Z ] [ INFO  ] [ matter.js / InteractionServer            ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime in field transitionTime
[ 2024-10-27T18:12:58.343Z ] [ ERROR ] [ matter.js / Transaction                  ]: Rolling back online#faebc06@3b70cf9f due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime
[ 2024-10-27T18:12:58.345Z ] [ INFO  ] [ matter.js / InteractionServer            ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime in field transitionTime
[ 2024-10-27T18:12:58.358Z ] [ INFO  ] [ matter.js / Behavior                     ]: Invoke 9dbe11de05e74c9db0ce63afedd6f511.aggregator.light_daniel_s_lamp_light.onOff.on online#faebc07@3b70cf9f (no payload)
```

**Comment by t0bst4r** [comment]
Thank you for reporting that issue!

I understand the problem, and I’ll check that in the next days.

**Comment by tobiimschrank** [comment]
Just to add something: one of my lights even showed a brightness level of "0" while it was turned on. Same for Samsung SmartThings. I think this might be related and maybe helps to find the bug :)

**Comment by t0bst4r** [comment]
I have added a fallback value for the "transitionTime", BUT for me it looks like that Google Home is actually doing a bad request.

How it works:
1. Google Home makes a request to the matter bridge.
2. Matter.js process this request and validates it
3. Matter.js passes the request to my LevelControl Implementation
4. My LevelControl implementation calls the Home-Assistant action **and passes the request to the level control base class**

My fallback value is added in step 4. If we are lucky, thatÄs enough. But if google is doing a bad request and the error occurs in step 2, then we have a problem.

**Comment by DMedina559** [comment]
Just tested, same issue.

```
[ 2024-10-29T20:58:42.409Z ] [ ERROR ] [ matter.js / Transaction                  ]: Rolling back online#5460841@3b70cf9f due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime
[ 2024-10-29T20:58:42.409Z ] [ INFO  ] [ matter.js / InteractionServer            ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime in field transitionTime
[ 2024-10-29T20:58:42.412Z ] [ ERROR ] [ matter.js / Transaction                  ]: Rolling back online#5460842@3b70cf9f due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime
[ 2024-10-29T20:58:42.412Z ] [ INFO  ] [ matter.js / InteractionServer            ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime in field transitionTime
[ 2024-10-29T20:58:42.414Z ] [ INFO  ] [ matter.js / Behavior                     ]: Invoke 9dbe11de05e74c9db0ce63afedd6f511.aggregator.light_daniel_s_lamp_light.onOff.on online#5460843@3b70cf9f (no payload)
[ 2024-10-29T20:58:42.416Z ] [ INFO  ] [ matter.js / Behavior                     ]: Invoke 9dbe11de05e74c9db0ce63afedd6f511.aggregator.light_daniel_s_room_light.onOff.on online#5460844@3b70cf9f (no payload)
```

**Comment by tobiimschrank** [comment]
Sorry, had no time to test it earlier: 

```
[ 2024-10-30T13:10:26.312Z ] [ INFO  ] [ matter.js / InteractionServer]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime in field transitionTime
[ 2024-10-30T13:10:26.310Z ] [ ERROR ] [ matter.js / Transaction]: Rolling back online#c68090e@7f57eead due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime
```

So it's really just the transition time (tested on alpha 10).
I don't receive an error or warning for the "0"-values for some of my bulbs. Even after I changed them in home assistant they stay at 0. Same bulb as others that work.
But as this bug has to do with the transitionTime I'm not sure if it is really related. ;)

**Comment by t0bst4r** [comment]
With `alpha.15` i released another workaround. Could you please test it again?

**Comment by DMedina559** [comment]
Alpha 13 everything is working except for the coolest color temp I get:

```
[ matter.js / InteractionServer                      ]: Error 0x87 while invoking command: Validating 9dbe11de05e74c9db0ce63afedd6f511.aggregator.light_daniel_s_lamp_light.colorControl.state: Constraint "colorTempPhysicalMinMireds to colorTempPhysicalMaxMireds": Value 153 is not within bounds defined by constraint (135)
```

I just tried with alpha 15 and same result. Everything is working now except for the coolest white temp, the other cool temp and all the warm temps work just fine

**Comment by Verteo** [comment]
For me it's not working and I have two different errors

When setting the brightness
```
[ 2024-11-01T13:34:28.027Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back online#92f91c4@cc7b7d49 due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field optionsMask
[ 2024-11-01T13:34:28.027Z ] [ INFO  ] [ matter.js / InteractionServer                      ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field optionsMask in field optionsMask
```

When setting the temperature
```
[ 2024-11-01T13:35:51.493Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back online#92f91cb@cc7b7d49 due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime
[ 2024-11-01T13:35:51.493Z ] [ INFO  ] [ matter.js / InteractionServer                      ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field transitionTime in field transitionTime
```

**Comment by t0bst4r** [comment]
For now i have raised an issue at `@project-chip/matter.js`:

https://github.com/project-chip/matter.js/issues/1348

**Comment by Apollon77** [comment]
see also https://github.com/project-chip/matter.js/pull/1332

**Comment by t0bst4r** [comment]
I don’t know where the lock-error is coming from, but you gave the same issues than the others:
- `Missing mandatory field transitionTime`
- `Missing mandatory field optionsMask`

As Apollon77 stated this is caused by invalid requests made by google home. This is a problem in the preview firmware of google nest. Please downgrade to the official firmware and the problem will be gone.

**Comment by KipK** [comment]
Seems the transitionTime has been fixed, there's still an error with optionMax:

```
 2024-11-02T11:30:27.952Z ] [ ERROR ] [ matter.js / Transaction                            ]: Rolling back online#907e0f1@88f90ed3 due to error: (ValidationMandatoryFieldMissingError/128) Missing mandatory field optionsMask
[ 2024-11-02T11:30:27.952Z ] [ INFO  ] [ matter.js / InteractionServer                      ]: Validation-Error 0x80 while invoking command: (ValidationMandatoryFieldMissingError/128) Missing mandatory field optionsMask in field optionsMask
```

Google Home has same firmware version for Preview and stable, so for now this feature is broken. 
Hope they will fix it soon.

**Comment by t0bst4r** [comment]
Somehow it started working for some users in #59 after updating everything.
They are not using the preview-firmware but faced similar issues before. Can someone here verify this?

**Comment by DMedina559** [comment]
Alpha 21, color changing, brightness and white temps are working. The coolest white doesn't seem to work tho 

[ 2024-11-07T14:47:58.649Z ] [ INFO  ] [ matter.js / InteractionServer                      ]: Error 0x87 while invoking command: Validating 9dbe11de05e74c9db0ce63afedd6f511.aggregator.light_daniel_s_room_light.colorControl.state: Constraint "colorTempPhysicalMinMireds to colorTempPhysicalMaxMireds": Value 153 is not within bounds defined by constraint (135)

**Comment by t0bst4r** [comment]
Can you provide the state attributes of your light? It should have some `min_color_temp_kelvin` and `max_color_temp_kelvin`. They are converted to mired and then used within matter for validation.

153 mireds should be 6535 K.

**Comment by t0bst4r** [comment]
Are you using the google home preview versions?

**Comment by DMedina559** [comment]
```
min_color_temp_kelvin: 2127
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 470
supported_color_modes: color_temp, hs, xy
color_mode: hs
brightness: 173
color_temp_kelvin: null
color_temp: null
hs_color: 256.535, 77.559
rgb_color: 111, 57, 255
xy_color: 0.198, 0.087
friendly_name: Lamp Light
supported_features: 32
```
These are the state attributes for my Nanoleaf matter over thread light, from HA's developer menu, and yes I'm enrolled in the general Google Home Preview and I believe some but not all my hubs are enrolled in the firmware preview

**Comment by t0bst4r** [comment]
okay. this looks more like a conversion problem. 
i am only taking the kelvin values because mireds are deprecated in HA.

max Kelvin: 6535 K => min mireds: 153.022
and 153 is lower than that 😀

**Comment by Apollon77** [comment]
Best Round it :-)

**Comment by t0bst4r** [comment]
Rounding is included in the latest release.
