### ISSUE TITLE
QR Code Doesn't Work from Bridge View

### ISSUE THREAD

**Issue by kramttocs** [t0bst4r/home-assistant-matter-hub#41]
The QR Code on the 8482 web ui bridge view doesn't get recognized. The code in the Add On logs does. The manual pairing code and other info is the same.

Android and Google Home.

**Comment by t0bst4r** [comment]
I just looked at the QR code, and it’s exactly the same… Also scanned it and it had the same content.

can you validate on your end if they are the same? E.g. with screenshots and/or scanning the code and comparing the content.

**Comment by kramttocs** [comment]
Showing my ignorance of how this is all working but adding screenshots isn't exposing anything that shouldn't be?

**Comment by t0bst4r** [comment]
We would still need to have access to your personal network.
Or you could cut both QR codes by half so that we only see the upper half 😀 

But if you don't want to share it, that's totally fine! 
Could you just verify it by yourself? Do the QR codes really look different? Or do you have multiple bridges and you just mixed up the QR codes 😀

**Comment by kramttocs** [comment]
I assumed it was all local but figured best to check.
I just created a new one (so it wasn't blocked by the Commissioned banner)
Top is webui. Bottom is add on log.
The top one doesn't even get recognized in the Google Home app.

![{F4FFDA24-EF02-42B9-AC31-48552BD127C6}](https://github.com/user-attachments/assets/b4cb0777-451f-4711-b45c-07dcb2f7de14)

![{3C34E06F-48A4-4A01-9250-19279EE36CEA}](https://github.com/user-attachments/assets/b3816862-ce43-4eef-9280-8df708cf6a0d)

**Comment by t0bst4r** [comment]
That's interesting... When i scan both, they have the exact same content. They still look different, but that's a thing that can happen with QR codes. But when the content is same they should both work.

I tried scanning them with my iPhone. Of course it won't work adding them to my home, but at least both got a suggestion "add to home". So they are recognized as "more or less" valid QR codes for matter.

**Comment by kramttocs** [comment]
Thanks (deleted them just because :) ) 

Strange that the top one scanned with yours and it doesn't with Google Home or my camera app.
Eh, not a big deal to me. Can see if anyone else reports the same or you can close this out. I am fine with either.
