### ISSUE TITLE
Bug cover inversion state in webinterface

### ISSUE THREAD

**Issue by ViaudJV** [t0bst4r/home-assistant-matter-hub#45]
I see in the web interface cover state 100% when my cover is close and 0% when cover is open.
HA and GoogleHome give 0% close and 100% open.

**Comment by t0bst4r** [comment]
That’s actually intended. 
Matter specifies open and close state in the opposite than Home Assistant.
It seems that google home is doing that as well, right? So it’s not a problem, right?
