### ISSUE TITLE
Not connecting with Smartthings

### ISSUE THREAD

**Issue by nehasjains** [t0bst4r/home-assistant-matter-hub#46]
Is this compatible with Smartthings?

I am trying to add devices to smartthings. But it is saying you need a hub to add to smartthings.

Am I doing something wrong here?

**Comment by t0bst4r** [comment]
SmartThings is compatible but a Samsung SmartThings Station or Samsung SmartThings Hub v2 and later are needed as a hub for Matter

see https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md#samsung-smartthings-ecosystem

**Comment by nehasjains** [comment]
Ok.. thank you so much
