### ISSUE TITLE
[Enhancement] Device type Water Leak Detector

### ISSUE THREAD

**Issue by aebgit** [t0bst4r/home-assistant-matter-hub#48]
Could you consider implementing the device type _Water Leak Detector_?
Water leak-sensors in Homeassistant are currently exported as contact-sensors. Apple Home can change the device-type only to door/window/contact-sensor, but not to Water Leak Detector.

Thanks!
Aebgit

PS: awesome project!! Already in alpha-state very useful.

**Comment by t0bst4r** [comment]
Can you provide the attributes of such an entity? (HA -> Dev Tools -> State -> search the entity)

Are Water Leak Detectors = moisture?
