### ISSUE TITLE
Include / Exclude should be exclusive not booth.

### ISSUE THREAD

**Issue by KipK** [t0bst4r/home-assistant-matter-hub#51]
Hi

I think if there's some include in the config, then everything else should be excluded. 

Same on the other side, if there's exclude , then everything else should be included.

You either choose how you want to filter your devices by including or excluding but it doesn't have much sense to have booth at the same time. 

As example I've made an include to all the lights with a specifig tag. 
And nothing in my exclude. I still have all the devices exposed on matter. 

Adding an exclude to the light domain , I then have no lights at all exposed, neither the tagged ones from the include.  

Or perhaps just having a priority on the include list to the exclude list, but I dont see a specific use case where we would need booth include and exclude.

**Comment by t0bst4r** [comment]
The current implementation works as follows:

- if there is no inclusion or at least one rule matches, then it's **included**
- if there is an exclusion, and if it an entity matches one of the rules, then it's **excluded**

An entity is used, if its included and not excluded.

> I think if there's some include in the config, then everything else should be excluded.
yes: if there is an inclusion, everything which does not match is excluded.

> Same on the other side, if there's exclude , then everything else should be included.
yes: if there is no inclusion, but an exclusion, everything which does not match the exclusion is included.

> As example I've made an include to all the lights with a specifig tag.
> And nothing in my exclude. I still have all the devices exposed on matter.
All the tagged devices? So it's working correct?

> Adding an exclude to the light domain , I then have no lights at all exposed, neither the tagged ones from the include.
Yes. That is how it's intended. The priority is implemented as "exclusion always wins".

Maybe i don't get the problem right, but **you don't have to use both**. Simply just use an inclusion rule (e.g. by label) that fits your needs.

**Comment by KipK** [comment]
So it's perhaps a bug , this has more sense :)

I have tested with this:

{
  "name": "Hass matter bridge",
  "port": 5540,
  "filter": {
    "include": [
      {
        "type": "label",
        "value": "Lumières"
      }
    ],
    "exclude": []
}

But all the Home assistant entities are still shared on the bridge, even the otehr lights that are not tagged.

**Comment by KipK** [comment]
I've also tested this:

`{
  "name": "Hass matter bridge",
  "port": 5540,
  "filter": {
    "include": [
      {
        "type": "label",
        "value": "Lumières"
      }
    ],
    "exclude": [
      {
        "type": "domain",
        "value": "automation"
      },
      {
        "type": "domain",
        "value": "script"
      },
      {
        "type": "domain",
        "value": "light"
      },
      {
        "type": "domain",
        "value": "switch"
      },
      {
        "type": "domain",
        "value": "lock"
      },
      {
        "type": "domain",
        "value": "fan"
      },
      {
        "type": "domain",
        "value": "binary_sensor"
      },
      {
        "type": "domain",
        "value": "sensor"
      },
      {
        "type": "domain",
        "value": "cover"
      },
      {
        "type": "domain",
        "value": "climate"
      },
      {
        "type": "domain",
        "value": "input_boolean"
      },
      {
        "type": "domain",
        "value": "scene"
      }
    ]
  }
}`

But no tagged "Lumières" entities where shared then

**Comment by KipK** [comment]
mhhh, I've just tested again with : 

```
{
  "name": "Hass matter bridge",
  "port": 5540,
  "filter": {
    "include": [
      {
        "type": "label",
        "value": "Lumières"
      }
    ],
    "exclude": []
  }
}
```

And now it displays 0 devices 

![image](https://github.com/user-attachments/assets/ba51cef6-c2ff-410f-a537-f71df1fbcedf)


I'll investigate a bit.

**Comment by t0bst4r** [comment]
You have to match the slug of the label and not its name.
Open Home Assistant -> Dev stools -> Template and enter `{{ labels() }}`

**Comment by KipK** [comment]
ahhh true that, it works as it should then :)

Thanks.

**Comment by 011V32** [comment]
Should be mentioned in the description 👍
