### ISSUE TITLE
[Bug] Template switches not being matched

### ISSUE THREAD

**Issue by marcovolpato00** [t0bst4r/home-assistant-matter-hub#58]
Hi, I tried adding [template switches](https://www.home-assistant.io/integrations/switch.template/) to the hub configuration but somehow they don't appear. The following is the hub configuration:
```json
"include": [
      {
        "type": "pattern",
        "value": "switch.all_alexa"
      },
      {
        "type": "label",
        "value": "all_alexa"
      },
      {
        "type": "domain",
        "value": "switch"
      },
    ]
```
As you can see, I tried including all kinds of filters, but the only switches found are the one that are not templates.

BTW thank you very much for your work 😃

**Comment by marcovolpato00** [comment]
Sorry, forgot to add that I'm using the docker image and not the addon. In any case, I've tried restarting the container but there are still no template switches

**Comment by t0bst4r** [comment]
In general it doesn't make any difference, where a device is coming from - if its any integration or a template.
Anyway i just validated that template switches in general work.

Maybe you can share a bit more details:
- number of bridges
- full configuration of the bridge
- screenshot of the bridge and its devices
- log while creating the bridge
- attributes of at least one missing template switch (HA -> Developer Tools -> State -> search for the entity -> Screenshot)

**Comment by marcovolpato00** [comment]
Found the problem! I figured that the only difference between my template switches (manually created in YAML file) and other switches, is that they do not have an unique ID, which is not mandatory.

After adding one in the `unique_id` field, they now appear in the bridge devices.

I'm guessing that somewhere in HASS APIs or in your code, entities without an unique ID get filtered out
