### ISSUE TITLE
[Network] can't find devices

### ISSUE THREAD

**Issue by magnetus26** [t0bst4r/home-assistant-matter-hub#60]
hello,
this looks like a great project, thanks for your time and effort.
however I cant connect my bridge to google home.
do I need my devices to be matter devices?
can this work with ESPhome?
thanks 
Miguel
![Capture](https://github.com/user-attachments/assets/c7f61e62-504f-48e4-9d72-3a2b508b0751)
![Capture2](https://github.com/user-attachments/assets/948b736c-40cd-4e63-a809-25eac730e3b8)

**Comment by t0bst4r** [comment]
No your devices do not need to be matter devices. That's the purpose of this project to publish ALL entities which you need from home assistant via matter.

Can you please share the logs of the addon when trying to pair?
Do you have any special network setup? E.g. VLAN to split Smart Home from normal network?

**Comment by nara1111** [comment]
There’s same situation in matterbridge.
Because of getting certificate of matter devices, including matter controllers, from CSA, sometimes uncerfiticated devices cannot register google home.

**Comment by kramttocs** [comment]
Do you have both 2.4 and 5ghz ssids? If so, connect to the 2.4ghz on your phone and try. Even if your Google device is on 5ghz.

**Comment by magnetus26** [comment]
OK.
I update to version 3.0.0-alpha.17 and now is working.
thanks everyone.
@kramttocs I was connected to 2.4 the whole time.
@t0bst4r no special network settings, about the logs, sorry my logs only goes to 1 minute of logs info, since I was able to connect now, dont have the logs from when it wasnt connected. 
is it there a way to retreave old logs?
thanks everyone,
Miguel

**Comment by Apollon77** [comment]
@nara1111 Thats partly right, but just follow the steps in https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md#google-home-ecosystem and you shoukld be still fine with Google ...

**Comment by nara1111** [comment]
@Apollon77 Well, first of all, thank you for your reference. I tried the instruction when I added matterbridge, and it worked. However, I tried it yesterday, it didn’t work for matterhub. I may try once again, by the way.

**Comment by Apollon77** [comment]
Then I would need full debug log from the matter.js side of things

**Comment by nara1111** [comment]
@Apollon77 Hello. I've added successfully after upgrading to alpha.15. Unfortunately, however, after upgrading to alpha.2x, the controller has not answered anymore.

quick question: where can I find log from the matter.js?

**Comment by nara1111** [comment]
@Apollon77 Oh, I've retried add controller with the pairing code from homekit, and it works fine. I added custom device in my google home console. :D
