### ISSUE TITLE
[Enhancement] Missing running state in Thermostat + enhancement

### ISSUE THREAD

**Issue by KipK** [t0bst4r/home-assistant-matter-hub#68]
Google home doesn't displays thermostats as running ( i e  dash icon in yellow mode + red heating / blue cooling icon displayed in UI. )
It looks like it's always off when heating. 
![image](https://github.com/user-attachments/assets/46c593e1-a855-405f-8862-c68ecf7a2083)

![image](https://github.com/user-attachments/assets/487b64cc-0084-43f8-a5bc-2314da623ce3)

Seems  climate "hvac_action" attribute is not exposed  throught it's matter equivalent.

Also I'm not sure it's supported on matter 1.3, but could you expose those climate HA attributes too if it is? 
 - current_humidity : google home wants it provided from the thermostat. If you have a thermostat in the same room as a humidity sensor, GH won't find  humidity data saying it doesn't find thermostat even if there's a humidity sensor in the same room.
- preset_modes : presets list 
- preset_mode : current selected preset 

Thanks

**Comment by KipK** [comment]
I gave a look on Matter 1.3 specs for thermostat.

I can confirm humidity is handled overRelative Humidity
Measurement cluster in thermostat device.

There's no specific preset cluster, but I feel the Scenes Management cluster use this role for thermostat.

**Comment by t0bst4r** [comment]
Not every climate has a humidity sensor, but we could add it optionally.

Is there any chance you already know the matter-equivalent to hvac_action? If not I need to find it myself. 😀

**Comment by t0bst4r** [comment]
> There's no specific presets cluster, but I feel the Scenes Management cluster use this role for thermostat.

this is interesting… I never touched scene management. Is that meant to be used for such cases?

**Comment by KipK** [comment]
> Not every climate has a humidity sensor, but we could add it optionally.
Yes, it should be exposed only if the humidity sensor is already present on the HA climate device.

> Is there any chance you already know the matter-equivalent to hvac_action? If not I need to find it myself. 😀

I'm not sure, the cluster doc is huge, I'll need to deep dive in it. 
I saw a SystemMode and ThermostatRunningMode attributes that could be a good candidates.

_4.3.9.25. SystemMode Attribute
This attribute SHALL indicate the current operating mode of the thermostat. Its value SHALL be
limited by the ControlSequenceOfOperation attribute._

and 

_4.3.9.27. ThermostatRunningMode Attribute
This attribute SHALL indicate the running mode of the thermostat. This attribute uses the same values as SystemModeEnum but can only be Off, Cool or Heat. This attribute is intended to provide
additional information when the thermostat’s system mode is in auto mode._

> this is interesting… I never touched scene management. Is that meant to be used for such cases?

It's a generic cluster mostly use for lights scene. But I saw thermostat have scene management cluster on 1.3 specs so the only use I see is for presets. This is not well documented. But we can test. :)

**Comment by KipK** [comment]
I can confirm the scene management cluster is not made for presettings. 

But, presets will be handled in Matter 1.4, it's just a matter of time.
https://9to5google.com/2024/11/07/matter-1-4-update-thermostat-more-devices/

**Comment by t0bst4r** [comment]
i just tried it out, but matter does not allow me to set `thermostatRunningMode`, so i need to dive deeper to find a workaround.

**Comment by t0bst4r** [comment]
regarding humidity and temperature, i added both clusters to climate devices (PR #76 ). If the HA entity does not support humidity, it will just have no value. We'll see how it looks then 😀 

Unfortunately i am facing some trouble with this PR. I am already in contact with the matterjs team.

**Comment by KipK** [comment]
Temperature is already exposed on thermostat clister so you don't need to add the temperature cluster I think

**Comment by t0bst4r** [comment]
Yes, but it seems to be optionally allowed. So why not give it a try 😀

**Comment by KipK** [comment]
> Temperature is already exposed on thermostat cluster so you don't need to add the temperature cluster I think

Have you checked how it's handled on z2m matter-bridge?

**Comment by t0bst4r** [comment]
I have just released the humidity feature.
Regarding running state: the z2m plugin is doing things generally different. I'll keep digging.

**Comment by t0bst4r** [comment]
Just found out, that thermostat running mode is only allowed to be set, if the climate supports "auto" mode. I can only test with a virtual climate which does not support "auto" mode.

I'll release it in some minutes.

**Comment by KipK** [comment]
I've posted on [the other thread](https://github.com/t0bst4r/home-assistant-matter-hub/issues/73#issuecomment-2466263449) a summerize of what to match between Matter and HA for thermostats

It's not ThermostatRunningMode but ThermostatRunningState we need :)

**Comment by KipK** [comment]
Also about the Humidity cluster, I think the humidity value needs te be an INT. I remember google home wouldn't display humidity when it was float. Not sure it's in the Matter specs, but that explains why displayed it few minutes then disappeared again. The value was round.
