### ISSUE TITLE
Creating Bridge

### ISSUE THREAD

**Issue by sierralx** [t0bst4r/home-assistant-matter-hub#72]
I make it work! 🔥 However, I can't see any way to update the bridge.
I am looking for a way to add additional "pattern" items or exclude certain lights.
Do you have any recommendations or an estimated time for the beta/final release? 🙌

{
"name": "Matterbridge",
"port": 5540,
"filter": {
"include": [
{
"type": "domain",
"value": "light"
},
{
"type": "domain",
"value": "cover"
},
{
"type": "pattern",
"value": "alarm_control_panel.sierra_homebase"
},
{
"type": "pattern",
"value": "climate.ecobee_thermostat"
}
],
"exclude": []
}
}

**Comment by t0bst4r** [comment]
Awesome! 🎉

I am currently working on the update feature (#25 ).
