### ISSUE TITLE
[Bug] State of door sensor not changing in google home

### ISSUE THREAD

**Issue by datvista** [t0bst4r/home-assistant-matter-hub#78]
My Door sensors not changing state on google home,  thank you.

**Comment by t0bst4r** [comment]
Can you please provide some logs of the addon? Please set the log level to "debug" in the addon configuration.
Additional please add some details to the logs WHEN you opened or closed the door.

**Comment by datvista** [comment]
[logs.txt](https://github.com/user-attachments/files/17678047/logs.txt)

**Comment by datvista** [comment]
![Screenshot_20241108-052644](https://github.com/user-attachments/assets/46b3ca73-1c10-4714-ae3f-49df12db576b)

**Comment by t0bst4r** [comment]
So..  the attached file only includes about 200ms of logs.

**Comment by datvista** [comment]
The state of the door sensor only changes every time the addon is restarted.

**Comment by Select446** [comment]
I also have this issue with all binary sensors connected for Alexa and Google, all doors and contacts worked yesterday but now only my switches update with binary sensors requiring a restart to update once - when using the matter-bridge webportal, switches show status change and update correctly in Alexa/Google but binary sensors dont change in either- version 3.0.0_alpha21

**Comment by lone-baggie** [comment]
Same issue here:

binary_sensor_patio_door_contact. I open and closed the door. No update until I restart 

[491eb00d_hamh_2024-11-08T15-33-34.806Z.log](https://github.com/user-attachments/files/17680775/491eb00d_hamh_2024-11-08T15-33-34.806Z.log)

**Comment by t0bst4r** [comment]
Thank you for the logs, @lone-baggie .
This was very helpful! I already fixed this one (alpha.22).
