### ISSUE TITLE
How to add devices?

### ISSUE THREAD

**Issue by nelsonamen** [t0bst4r/home-assistant-matter-hub#8]
![17300705802978712896544543587413](https://github.com/user-attachments/assets/9d6db069-0e25-4b76-bfa9-e4ec4c72da01)
 How to add divices? + Dont work

And how to edit?

**Comment by Lackmake** [comment]
Same here. Cant get devices to show up

**Comment by huyhpa** [comment]
I got the same error. Tried creating a second bridge with port 5541, and it worked.

**Comment by t0bst4r** [comment]
Can you please share your config?
What do your includes and excludes look like?

**Comment by nhok3296** [comment]
> Can you please share your config? What do your includes and excludes look like?

`{
  "name": "My Hub",
  "port": 5540,
  "filter": {
    "include": [
      {
        "type": "pattern",
        "value": "switch.0x00158d0002fb5476_switch"
      },
      {
        "type": "pattern",
        "value": "switch.pn1_2"
      },
      {
        "type": "pattern",
        "value": "switch.pn2_2"
      },
      {
        "type": "pattern",
        "value": "group.light"
      },
      {
        "type": "pattern",
        "value": "switch.bep_1"
      },
      {
        "type": "pattern",
        "value": "switch.bep_2"
      },
      {
        "type": "pattern",
        "value": "switch.cua_1"
      },
      {
        "type": "pattern",
        "value": "switch.cua_2"
      },
      {
        "type": "pattern",
        "value": "switch.pk_1"
      },
      {
        "type": "pattern",
        "value": "switch.pn1_1"
      },
      {
        "type": "pattern",
        "value": "switch.pn2_1"
      },
      {
        "type": "pattern",
        "value": "climate.wc_1"
      },
      {
        "type": "pattern",
        "value": "climate.wc_2"
      },
      {
        "type": "pattern",
        "value": "climate.wc_3"
      },
      {
        "type": "pattern",
        "value": "climate.ac_1"
      },
      {
        "type": "pattern",
        "value": "climate.ac_2"
      },
      {
        "type": "pattern",
        "value": "climate.ac_3"
      },
      {
        "type": "pattern",
        "value": "vacuum.viomi_v7_2699_robot_cleaner"
      },
    ],
    "exclude": []
  }
}`

**Comment by t0bst4r** [comment]
Okay, this doesn't look wrong - except the comma AFTER the LAST entry in the include section. But I'd expect that to fail when creating the bridge. If that already worked this could be a typo here in the issue.

This wont work, since group is not a supported domain:
```
      {
        "type": "pattern",
        "value": "group.light"
      },
```

**Comment by nhok3296** [comment]
> Okay, this doesn't look wrong - except the comma AFTER the LAST entry in the include section. But I'd expect that to fail when creating the bridge. If that already worked this could be a typo here in the issue.
> 
> This wont work, since group is not a supported domain:
> 
> ```
>       {
>         "type": "pattern",
>         "value": "group.light"
>       },
> ```
> 
> do you see any errors in the logs?

`s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[ 2024-10-28T15:51:08.364Z ] [ INFO  ] [ Storage                                  ]: Storage location: /config/data
[ 2024-10-28T15:51:08.487Z ] [ INFO  ] [ matter.js / ServerStore                  ]: Opened 68db54ce64364d68b428181947feb773 storage at /config/data/68db54ce64364d68b428181947feb773
[ 2024-10-28T15:51:09.196Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773 ready endpoint#: 0 type: RootNode (0x16) behaviors: 💤parts ✔index ✔basicInformation ✔accessControl ✔groupKeyManagement ✔generalCommissioning ✔administratorCommissioning ✔operationalCredentials ✔generalDiagnostics ✔commissioning ✔network 💤productDescription 💤sessions ✔descriptor
[ 2024-10-28T15:51:09.208Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator ready endpoint#: 1 type: Aggregator (0xe) behaviors: 💤parts ✔index ✔descriptor
[ 2024-10-28T15:51:09.228Z ] [ INFO  ] [ matter.js / Node                         ]: 68db54ce64364d68b428181947feb773 going online
[ 2024-10-28T15:51:09.493Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_0x00158d0003a3501f ready endpoint#: 2 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.517Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_0x00158d0002ed908c_switch ready endpoint#: 3 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.541Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_0x00158d0002fb5476_switch ready endpoint#: 4 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.561Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_0x60a423fffedb3e64_left ready endpoint#: 5 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.584Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_wc_2 ready endpoint#: 6 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.604Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_wc_1 ready endpoint#: 7 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.631Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_wc_3 ready endpoint#: 8 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.652Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pk_1 ready endpoint#: 9 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.673Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pk_2 ready endpoint#: 10 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.693Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pn2_3 ready endpoint#: 11 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.721Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pn2_2 ready endpoint#: 12 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.742Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pn2_1 ready endpoint#: 13 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.763Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_0x00158d0002ed908c_power_outage_memory ready endpoint#: 14 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.785Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_0x00158d0003a3501f_power_outage_memory ready endpoint#: 15 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.807Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_0x00158d0002fb5476_power_outage_memory ready endpoint#: 16 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.838Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pn1_1 ready endpoint#: 17 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.859Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pn1_2 ready endpoint#: 18 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.880Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_pn1_3 ready endpoint#: 19 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.901Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_bep_1 ready endpoint#: 20 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.920Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_bep_2 ready endpoint#: 21 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.948Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_bep_3 ready endpoint#: 22 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.967Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_cua_1 ready endpoint#: 23 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:09.986Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_cua_2 ready endpoint#: 24 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:10.008Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_baodong ready endpoint#: 25 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
[ 2024-10-28T15:51:10.029Z ] [ INFO  ] [ matter.js / Endpoint                     ]: 68db54ce64364d68b428181947feb773.aggregator.switch_zigbee2mqtt_bridge_permit_join ready endpoint#: 26 type: OnOffPlugInUnit (0x10a) behaviors: ✔identify ✔groups ✔onOff ✔bridgedDeviceBasicInformation ✔descriptor
home-assistant-matter-hub start

start the application

Options:
  --help                         Show help                             [boolean]
  --log-level
          [string] [choices: "debug", "info", "warn", "error"] [default: "info"]
  --disable-log-colors                                [boolean] [default: false]
  --storage-location             Path to a directory where the application shoul
                                 d store its data. Defaults to $HOME/.home-assis
                                 tant-matter-hub                        [string]
  --web-port                     Port used by the web application
                                                        [number] [default: 8482]
  --home-assistant-url           The HTTP-URL of your Home Assistant URL
                                                             [string] [required]
  --home-assistant-access-token  A long-lived access token for your Home Assista
                                 nt Instance                 [string] [required]

TypeError: Cannot read properties of undefined (reading 'state')
    at _OnOffServer.createState (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1090:24)
    at new SwitchDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:1561:32)
    at switch (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2665:25)
    at createDevice (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2644:10)
    at Bridge.createDevices (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2737:26)
    at async Bridge.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2729:9)
    at async BridgeService.start (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:2804:11)
    at async handler (file:///usr/local/lib/node_modules/home-assistant-matter-hub/dist/backend/cli.js:3307:5)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

**Comment by t0bst4r** [comment]
Okay, I see. It’s the same problem as in #11 
I‘ll close this one and copy your error log over there.
