### ISSUE TITLE
Wiki or Discussion tab in repo

### ISSUE THREAD

**Issue by 011V32** [t0bst4r/home-assistant-matter-hub#86]
Hello.
I wanted to ask whether you think a Wiki or Discussions tab would make sense for this repo?
At least I don't know where the best place to ask my questions is at the moment.
The logs also mention the Discord chat, but I don't know which one?
Thx.

**Comment by t0bst4r** [comment]
For now i have added discussions to this project. Where does this discord message come from? Could be a message printed by home assistant itself.
