### ISSUE TITLE
Can't control air conditioner from Google home

### ISSUE THREAD

**Issue by datvista** [t0bst4r/home-assistant-matter-hub#91]
Can't control air conditioner from Google home even though status is still updated

**Comment by datvista** [comment]
[logs-2.txt](https://github.com/user-attachments/files/17685998/logs-2.txt)

**Comment by t0bst4r** [comment]
This is a duplicate of #73 
I have already build a fix, but due to some small issue it's not yet released.

**Comment by datvista** [comment]
Thank you
