### ISSUE TITLE
[Enhancement] Integrate humidity value to temperature sensor and climate device

### ISSUE THREAD

**Issue by EagleDev91** [t0bst4r/home-assistant-matter-hub#96]
Hi,

is it possible to integrate humidity value to its associated temperature sensor or climate device? At least Google Home (i cannot speak about others systems) can combine/list both in one device.

I would really appreciate it, so far it is possible :)

**Comment by t0bst4r** [comment]
I am currently working on a refactoring of the climate device, to fix several bugs. This will indeed include the climate's humidity, too. #76

**Comment by EagleDev91** [comment]
Awesome, thank you!
