### ISSUE TITLE
[Enhancement] Support https:// on Configuration web page

### ISSUE THREAD

**Issue by lone-baggie** [t0bst4r/home-assistant-matter-hub#98]
My HA uses a SSL certificate. Get an error when trying to link from Open WEbUI 

This site can’t be reached

Nothing major can use use local IP , just get a not secure  warning . Would be nice if configuration web page could use existing certificate

**Comment by DJBenson** [comment]
This would be fixed by #36.

**Comment by myevit** [comment]
waiting as well

**Comment by tam481** [comment]
@t0bst4r please include this in the next update. You were able to quickly add it to the original project.

**Comment by t0bst4r** [comment]
I need to implement ingress support anyway - then home assistant takes care of ssl. And for people running docker, I’d recommend using a reverse proxy anyway which takes care of certificate renewal etc. I‘ll add an option to limit http access to a specific ip (range) in order to block all traffic which is not the proxy. 

What do you think? Would that be sufficient? Or is in-app SSL required?

**Comment by tam481** [comment]
Sorry @t0bst4r I think I may have misunderstood the request. 
My Home Assistant is behind a reverse-proxy (Traefik) which is configured to redirect http to https. 
I am unable to connect to HASS on https://domain.name

I can do that with the current Matterbridge but not this new one (Matterhub)

p.s. Traefik is taking care of the certificate renewal.

**Comment by myevit** [comment]
![image](https://github.com/user-attachments/assets/e3a0c03c-6fcc-484c-a666-20a6a7e33245)
same for me. https://myowndomain.com:8482 
it should be the port - it  should be ingress. like for example haas google backup addon 
alternative you can always open web ui in new page using http+ip-address+port

**Comment by DJBenson** [comment]
> Sorry @t0bst4r I think I may have misunderstood the request. 
> 
> My Home Assistant is behind a reverse-proxy (Traefik) which is configured to redirect http to https. 
> 
> I am unable to connect to HASS on https://domain.name
> 
> 
> 
> I can do that with the current Matterbridge but not this new one (Matterhub)
> 
> 
> 
> p.s. Traefik is taking care of the certificate renewal.

How are you accessing HA then? The reverse proxy just puts everything web facing behind it but you still access it via a domain name? Ingress support would negate the need to expose the 84xx port as it would sit "inside" Home Assistant like other addons do (like zigbee2mqtt, frigate etc.)

**Comment by DJBenson** [comment]
> same for me. when I open web ui by link it goes to ->  https://myowndomain.com:8482 
> 
> it should be the port - it should be ingress. like for example haas google backup addon 
> 
> alternative you can always open web ui in new page using http+ip-address+port 

Yeah as per my other reply, ingress would negate the need to expose port 8482 at all, it would just sit as a directory under your main HA domain. If people then have a reverse proxy in front of HA it would work the same. 

I use Cloudflare Tunnels and my HA domain (and all the addons which support ingress) all work natively.

**Comment by myevit** [comment]
ingress controllrer (for my inhouse) I use Nginx Proxy Manager, for external access Cloudflare Tunnel. In both cases hass exposed just https://mydomain.com. this is the same as mydomain.com:443, so you can't add custom port as it will make ingress controlled reject your request and browser will complain. to baypass this, in hass there as own "ingess path"  https://mydomain.com/hassio/ingress/cebe7a76_hassio_google_drive_backup that will be patched though reverse proxy, with ssl termination and later haas will patch it to addon/docker container port. 
essentially it's addon/haas feature

**Comment by tam481** [comment]
Isn't Traefik or any other reverse proxy the ingress controller?
I just need Matterhub to be able to connect to Home Assistant via Traefik in the same way that the current Matterbridge can.

**Comment by DJBenson** [comment]
> Isn't Traefik or any other reverse proxy the ingress controller?
> 
> I just need Matterhub to be able to connect to Home Assistant via Traefik in the same way that the current Matterbridge can.

Ingress is how Home Assistant embeds addons so they use HA authentication and are proxied under HA's root domain/port or IP/port. Putting another proxy on top is fine but the two are not the same thing. 

The hub does not communicate with home assistant via a proxy, it uses internal docker networking so far as I know, so getting the two to "talk" is nothing to do with proxies. Being able to access the hub's web interface IS a where a proxy comes in handy as you can have the whole lot under one domain.

For a totally local install, no proxy is required to allow HA and HAMH to work.

**Comment by DJBenson** [comment]
> Isn't Traefik or any other reverse proxy the ingress controller?
> 
> I just need Matterhub to be able to connect to Home Assistant via Traefik in the same way that the current Matterbridge can.

Are you running HA and HAMH on the same host? Using the addon?

**Comment by t0bst4r** [comment]
Ingress is now implemented and SSL will be handled by home assistant itself.
When running the app in custom docker or differently one can use a reverse proxy to enable https.

Additionally, an IP whitelist can be configured. With that the container can only be reached through the reverse proxy - even with host network mode.

**Comment by t0bst4r** [comment]
@tam481  

you are running home assistant behind a reverse proxy, right?
and home assistant is not reachable by the hub-container, right? Is there any error message you get?
does the reverse proxy use valid ssl certificates and not self signed?

please open a new issue for this if necessary.

**Comment by myevit** [comment]
I have 503: Service Unavailable
<img width="359" alt="Screenshot 2024-11-30 at 10 01 43 AM" src="https://github.com/user-attachments/assets/ff166708-bac8-4c13-ae16-e7e32d7f508b">

**Comment by t0bst4r** [comment]
Please see #230 for details.

**Comment by DJBenson** [comment]
Absolute legend @t0bst4r 😎
